### ISSUE TITLE
fromEither :: b -> Either a b -> b

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#130]
This was suggested by @Bpless as a way to extract the `b` from a value of type `Either a b`. It's analogous to [`fromMaybe :: a -> Maybe a -> a`][1].

Usage:

```javascript
> S.fromEither(NaN, S.Left('XXX'))
NaN

> S.fromEither(NaN, S.Right(42))
42
```

[1]: https://github.com/plaid/sanctuary#fromMaybe

**Comment by svozza** [comment]
Oh nice, I'd really like this function.
