### ISSUE TITLE
Type Safe Ramda Functions

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#145]
As mentioned in #141, let's start try to get a list of typesafe functions we want from Ramda. I've put together a list of way too many functions that we can whittle down here as people chip in with their views.

- [x] [`R.append`](http://ramdajs.com/docs/#append)
- [x] [`R.concat`](http://ramdajs.com/docs/#concat)
- [ ] [`R.contains`](http://ramdajs.com/docs/#contains)
- [ ] [`R.equals`](http://ramdajs.com/docs/#equals)
- [ ] [`R.filter`](http://ramdajs.com/docs/#filter)
- [ ] [`R.fromPairs`](http://ramdajs.com/docs/#fromPairs)
- [x] [`R.keys`](http://ramdajs.com/docs/#keys)
- [ ] <del>[`R.length`](http://ramdajs.com/docs/#length)</del>
- [x] [`R.max`](http://ramdajs.com/docs/#max)
- [x] [`R.mean`](http://ramdajs.com/docs/#mean)
- [ ] [`R.median`](http://ramdajs.com/docs/#median)
- [ ] <del>[`R.merge`](http://ramdajs.com/docs/#merge)</del>
- [ ] [`R.mergeAll`](http://ramdajs.com/docs/#mergeAll)
- [x] [`R.min`](http://ramdajs.com/docs/#min)
- [ ] <del>[`R.modulo`](http://ramdajs.com/docs/#modulo)</del>
- [ ] [`R.omit`](http://ramdajs.com/docs/#omit)
- [x] [`R.prepend`](http://ramdajs.com/docs/#prepend)
- [x] [`R.product`](http://ramdajs.com/docs/#product)
- [x] [`R.range`](http://ramdajs.com/docs/#range)
- [x] [`R.reduce`](http://ramdajs.com/docs/#reduce)
- [ ] [`R.reject`](http://ramdajs.com/docs/#reject)
- [x] [`R.reverse`](http://ramdajs.com/docs/#reverse)
- [ ] [`R.scan`](http://ramdajs.com/docs/#scan)
- [ ] [`R.split`](http://ramdajs.com/docs/#split)
- [x] [`R.sum`](http://ramdajs.com/docs/#sum)
- [x] [`R.toPairs`](http://ramdajs.com/docs/#toPairs)
- [x] [`R.trim`](http://ramdajs.com/docs/#trim)
- [x] [`R.values`](http://ramdajs.com/docs/#values)
- [ ] [`R.when`](http://ramdajs.com/docs/#when)
- [ ] [`R.unless`](http://ramdajs.com/docs/#unless)
- [ ] [`R.zip`](http://ramdajs.com/docs/#zip)
- [ ] [`R.zipObj`](http://ramdajs.com/docs/#zipObj)

Something I'm not clear on though is how we deal with functions that accept both arrays and string. Do we need a new type?

**Comment by davidchambers** [comment]
I think we can tick the box beside [`R.nth`][1] since we already have [`S.at`][2].

Is there a reason you included [`R.when`][3] but not [`R.unless`][4]?

> Something I'm not clear on though is how we deal with functions that accept both arrays and string. Do we need a new type?

This should be possible. For example:

```haskell
concat :: Semigroup a => a -> a -> a
```


[1]: http://ramdajs.com/docs/#nth
[2]: https://github.com/plaid/sanctuary#at
[3]: http://ramdajs.com/docs/#when
[4]: http://ramdajs.com/docs/#unless

**Comment by svozza** [comment]
> I think we can tick the box beside R.nth since we already have S.at.

Ah yes, of course.

> Is there a reason you included R.when but not R.unless?

Oops, no, just an oversight. Fixed.

**Comment by jethrolarson** [comment]
I assume that your concat would ensure that both arguments are the same type, right?

**Comment by davidchambers** [comment]
> I assume that your concat would ensure that both arguments are the same type, right?

That's right, @jethrolarson:

```javascript
const $ = require('sanctuary-def');

const def = $.create(true, $.env);

//    a :: Type
const a = $.TypeVariable('a');

//    Semigroup :: TypeClass
const Semigroup = $.TypeClass(
  'sanctuary/Semigroup',
  x => x != null && typeof x.concat === 'function'
);

//    concat :: Semigroup a => a -> a -> a
const concat =
def('concat',
    {a: [Semigroup]},
    [a, a, a],
    (x, y) => x.concat(y));

concat('abc', 'def');
// => 'abcdef'

concat([1, 2, 3], [4, 5, 6]);
// => [1, 2, 3, 4, 5, 6]

concat('abc', [1, 2, 3]);
// ! TypeError: ‘concat’ expected a value of type String as its second argument; received [1, 2, 3]

concat(['a', 'b', 'c'], [1, 2, 3]);
// ! TypeError: ‘concat’ expected a value of type (Array String) as its second argument; received [1, 2, 3]
```

**Comment by svozza** [comment]
So, I'm trying to implement `S.length` and this issue of types that work on lists and strings won't be resolved by relying on the `Semigroup` type. If we restrict `S.length` in this way then that means that the function should work on `Either` types, which of course don't have a `length` property. It also means that it won't operate on the `Function` type. If we could treat strings as lists of characters then we could just use the `Functor` type class but that's not an option here.

**Comment by jethrolarson** [comment]
Yeah, semigroup doesn't give you index or length. Array-like does but
that's not mathy :)

**Comment by svozza** [comment]
Ha. Yes, I was hoping not to go down that route...

**Comment by joneshf** [comment]
Array-like can mostly be approximated by `Foldable` because you can define `toArray`: https://github.com/fantasyland/fantasy-land/#foldable

So you could have length. Though i'm not exactly sure how to type it with `sanctuary-def`:

```js
// length : Foldable f => f a -> NonNegativeInteger
function length(x) {
  return x.reduce((state, _) => state + 1, 0);
}
```

Are there any examples in `sanctuary-def` of typeclasses with higher kinded types? I see the test for `Monad`, but it's a test of the bad case.

**Comment by davidchambers** [comment]
One straightforward solution is a "Countable" type class which checks whether a given value has a valid `length` property. I like where @joneshf is going with Foldable, though.

> Are there any examples in `sanctuary-def` of typeclasses with higher kinded types?

I believe higher-kinded types to be doable, but sanctuary-def don't yet support them.

**Comment by svozza** [comment]
Something that was mentioned in the Gitter room was how this issue is a good gateway for people looking to contribute for the first time. It got me thinking that it might be cool to do what they do on the nodejs project and split some of this function list into individual issues and label them with the tag 'good first contribution' like [this](https://github.com/nodejs/node/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+contribution%22). What do people think?

**Comment by davidchambers** [comment]
Great idea, Stefano!

**Comment by gilligan** [comment]
yeah these are totally `"low hanging fruits"` and I really like that suggestion Stefano ;)

**Comment by davidchambers** [comment]
I'll close this issue. We've added many of the important functions, and #216 will add a handful more. Don't hesitate to open an issue if there's a particular Ramda function you'd like sanctified. :)

**Comment by futpib** [comment]
@davidchambers, do you have something like `R.fromPairs`?

**Comment by davidchambers** [comment]
Sanctuary doesn't yet provide such a function, @futpib. Are you interested in working on a pull request to add it?

**Comment by futpib** [comment]
@davidchambers #454 poof

**Comment by Fl4m3Ph03n1x** [comment]
Why was R.modulo removed?

**Comment by davidchambers** [comment]
> Why was R.modulo removed?

Because sanctuary-int provides both [`rem`][1] and [`mod`][2]. :)


[1]: https://github.com/sanctuary-js/sanctuary-int#rem
[2]: https://github.com/sanctuary-js/sanctuary-int#mod
