### ISSUE TITLE
Type validation using predicates rather than TypeRep's

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary#149]
Since most type-checking libraries provide convenient ways to get the predicate for a type, this would allow for much greater interoperability with run-time type systems.

With Sanctuary:

``` js
const isInt = allPass([is(Number), x => x % 1 === 0]);

get(isInt, 'x', {x: 0.5}); //-> Nothing
```

With TComb:

``` js
const Int = t.refinement(t.Number, x => x % 1 === 0, 'Int');

get(Int.is, 'x', {x: 0.5}); //-> Nothing
```

With Sanctuary Def:

``` js
const Int = $.NullaryType('my/Int', allPass([is(Number), x => x % 1 === 0]));

get(Int.test, 'x', {x: 0.5}); //-> Nothing
```

The possibilities are _endless!_ Another option is to accept Sanctuary Def types, which would make the code a little more concise, but the possibilities slightly less endless.

**Comment by davidchambers** [comment]
> Another option is to accept Sanctuary Def types, which would make the code a little more concise, but the possibilities slightly less endless.

I'd like to keep the possibilities endless. :)

I'd like it to remain possible to use Sanctuary without sanctuary-def. It's nice that one could preserve the current behaviour simply by replacing `S.get(X)` with `S.get(S.is(X))`.

This change would let us replace `TypeRep b` with `(Any -> Boolean)` in several type signatures. Sanctuary-specific things make me uneasy. Predicates are commonplace.

**Comment by svozza** [comment]
How would this feature work with https://github.com/plaid/sanctuary-def/pull/28?

**Comment by Avaq** [comment]
@svozza I would imagine `$.Type.test` would still be an operational predicate even if automatic run-time type-checking is turned off. This feature is about explicit type-checking, you wouldn't want that turned off even in production because the behaviour of your program depends on it, eg:

```js
pipe([
  gets($.Array.test, ['response', 'body']),
  maybeToEither(new Error('Expected response body to be an array'))
])
```

Wouldn't want this to behave any differently in production.

**Comment by svozza** [comment]
Fair enough, makes sense. I would go the other way though and not mix the concerns of validating types with those of getting a value and have this as a separate function in the pipeline.

**Comment by Avaq** [comment]
Like I said in #150, I do think that would be more elegant. But I'm really quite fond of the way these functions *force* me to do type validation where appropriate once you "mix the concerns".

**Comment by davidchambers** [comment]
> I'm really quite fond of the way these functions *force* me to do type validation

I am too. This was the motivation for adding the type arguments in #64.

**Comment by davidchambers** [comment]
Are you interested in working on these changes, @Avaq?

**Comment by Avaq** [comment]
I am, but I haven't found the time yet. If I *do* start work on it I'll leave a notice. Until then you're free to pick it up instead, if you have the time. Let me know if you do. :)

**Comment by davidchambers** [comment]
I'll leave this one for you. There are plenty of other issues to keep me occupied for the time being. :)

**Comment by Avaq** [comment]
:information_source: I started working on this.

**Comment by Avaq** [comment]
Oh! Of course! I could've just assigned myself. ;)

**Comment by davidchambers** [comment]
No worries. I appreciated the `:information_source:` emoji. :)
