### ISSUE TITLE
ToC in readme

### ISSUE THREAD

**Issue by dalgard** [sanctuary-js/sanctuary#156]
It would be helpful with a table of contents in the readme docs. I tried generating one with [DocToc](https://github.com/thlorenz/doctoc), but it choked on the markup of the function signatures.

Before I try to work around it – are you interested in getting a PR for it at all?

**Comment by davidchambers** [comment]
A table of contents would be useful, certainly. Listing every function is perhaps unnecessary, but it would be great to list the sections and to be able to jump to a particular section. :)

If we decide not to list every function, we may not need to introduce a dependency:

```console
$ sed -e '/^#\{2,3\} /!d' -e 's/^###/    -/' -e 's/^##/  -/' README.md
  - Types
    - Accessible pseudotype
    - Integer pseudotype
    - List pseudotype
    - Type representatives
  - API
    - Classify
    - Combinator
    - Function
    - Composition
    - Maybe type
    - Either type
    - Alternative
    - Logic
    - List
    - Object
    - Parse
    - RegExp
    - String
```

It's worth noting that I've begun work on a website for Sanctuary, though this is an orthogonal issue as the readme would benefit from a table of contents irrespective of whether there exists a website which presents the information more effectively.

**Comment by davidchambers** [comment]
Now that we have sanctuary-js/sanctuary-site#13 I don't think it's necessary to update the readme as well. The nice thing about having the readme on GitHub is that it provides documentation for Sanctuary versions prior to the current one. The [website][1] is the best place to learn about the current Sanctuary version, though, as it has interactive usage examples. :)


[1]: https://sanctuary.js.org/
