### ISSUE TITLE
Github Autosquash

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#186]
Should we enable this feature to save contributors constantly having to squash and rebase their commits into 1?

https://github.com/blog/2141-squash-your-commits

**Comment by davidchambers** [comment]
I believe the feature is already enabled. I'm open to using it, but I don't think we should *force* squashing. It's rare, but there are occasions when a pull request should legitimately contain multiple atomic commits.

**Comment by benperez** [comment]
The only downside to enabling but not requiring autosquashing is that the default option is still to create a merge commit. You have to click the tiny arrow in the merge button that appears when you're confirming. If we want to squash by default but sometimes allow merge commits then we could make squash the only option and enable merge commits in those special scenarios.

**Comment by davidchambers** [comment]
Oh. It seems I misunderstood commit squashing. I didn't realize that it *also* avoids a merge commit. The merge commit is very useful, though, as it's the only way to get to a pull request from a commit log (as you are no doubt aware, Ben, from your work on :dromedary_camel:).

Can someone provide a link to a pull request squashed via the GitHub UI?

**Comment by benperez** [comment]
So I just tested this feature in one of my personal projects. You can see an example of the result of doing an autosquash of a branch with 2 commits [here](https://github.com/benperez/chinese-poker/commit/7a3a697df02a5aeea344188183c8df706eed00ca). The PR number and link are actually both in the message of the single commit that's generated. I personally find this to be pretty clean looking.

**Comment by davidchambers** [comment]
I've decided not to make use of this feature, for three reasons:

  - I like to avoid touching commits authored by other people;
  - were a "squashed" commit to fail CI the PR would appear to have been merged with failing tests; and
  - `master` would not be a superset of the feature branch post merge, which would break my workflow (merge via GitHub, `git checkout master`, `git pull origin master`, `git branch -d <branch>`, `git push origin :<branch>`).
