### ISSUE TITLE
Add S.median function

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#195]
Create a typesafe version of [R.median](http://ramdajs.com/docs/#median)

**Comment by davidchambers** [comment]
This is a bit trickier than it looks. We should accept any `(Foldable f, Ord a) => f a`. For example:

```javascript
> S.median(['r', 'a', 'm', 'd', 'a'])
Just('d')
```

**Comment by davidchambers** [comment]
I don't think this function warrants inclusion.
