### ISSUE TITLE
Add S.modulo function

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#199]
Create a typesafe version of [R.modulo](http://ramdajs.com/docs/#modulo).

**Comment by davidchambers** [comment]
We do have [`S.Int.rem`][1] and [`S.Int.mod`][2]:

```haskell
S.Int.rem :: Int -> NonZeroInt -> Int
S.Int.mod :: Int -> NonZeroInt -> Int
```

We could add [Integer][3] versions of the above to Sanctuary proper:

```haskell
S.rem :: Integer -> NonZeroInteger -> Integer
S.mod :: Integer -> NonZeroInteger -> Integer
```

We'd want to define `$.NonZeroInteger` before doing so.


[1]: https://github.com/sanctuary-js/sanctuary-int/#rem
[2]: https://github.com/sanctuary-js/sanctuary-int/#mod
[3]: https://github.com/sanctuary-js/sanctuary-def/#integer
