### ISSUE TITLE
eitherToMaybe :: Either a b -> Maybe b

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#203]
@kedashoe added [`maybeToEither`][1] in #76. It would be nice to provide a function for going in the other direction. The implementation is not complex, and already appears in the [test suite][2]:

> ```javascript
> //  eitherToMaybe :: Either a b -> Maybe b
> var eitherToMaybe = S.either(S.K(S.Nothing()), S.Just);
> ```

[1]: http://sanctuary.js.org/#maybeToEither
[2]: https://github.com/sanctuary-js/sanctuary/blob/v0.10.0/test/index.js#L117-L118

**Comment by Guang1234567** [comment]
```haskell
maybeToEither :: a -> Maybe b -> Either a b
maybeToEither = flip maybe Right . Left

eitherToMaybe :: Either a b -> Maybe b
eitherToMaybe = either (const Nothing) Just
```

**Comment by davidchambers** [comment]
Those are elegant implementations, @Guang1234567. Is that the reason you shared them?
