### ISSUE TITLE
Value coverage

### ISSUE THREAD

**Issue by rjmk** [sanctuary-js/sanctuary#208]
It's cool that Sanctuary has code-coverage, but I'm even keener on some sort of value coverage guarantee. Is there any interest in implementing property testing with something like [JSVerify](https://github.com/jsverify/jsverify)?

**Comment by davidchambers** [comment]
> Is there any interest in implementing property testing with something like [JSVerify](https://github.com/jsverify/jsverify)?

Absolutely! We've dipped our toes into property-based testing (#113, #121). I'd *love* to see more tests of this nature. :)

Have you any interest in writing some tests, @rjmk?

**Comment by rjmk** [comment]
For sure! I guess I'll just pick a section of Sanctuary and dive in

**Comment by davidchambers** [comment]
Sounds good! @svozza did some work on writing property-based tests for Ramda. I believe he'd suggest that you write tests for one property at a time, opening pull requests along the way. Writing tests for all the properties at once would be a big undertaking!

**Comment by svozza** [comment]
I think you might be confusing me with @gilligan, David. Here's the PR you're referring too:

https://github.com/ramda/ramda/pull/1540

**Comment by davidchambers** [comment]
You're absolutely right, Stefano! That explains why I couldn't find the pull request. Thanks for setting me straight. :)

**Comment by Koleok** [comment]
This is slightly off topic, but i want to bounce this idea. I have been using both `sanctuary` and `jsverify` a lot in tandem, and i feel like there is an opportunity for an adapter module that just declares all the obvious relationships between sanctuary's `types` and jsverify's `arbs`.

This way you only have to specify the expression for each `property` and not re-state the signature defined with `def`.

It obviously would not work out of the box with more complex arbitraries and types, but it seems straightforward to establish these relationships for all the primitives.

**Comment by davidchambers** [comment]
That's a very cool idea, @Koleok! I'd love to see such a module.

**Comment by davidchambers** [comment]
We're making more use of JSVerify now (see, for example, the property-based tests added in #323). It would be valuable to increase the number of property-based tests further still. This issue is too open-ended, though, so I'll close it. Thank you @rjmk for prompting this discussion. :)
