### ISSUE TITLE
Idea: Create Pair Programming Videos

### ISSUE THREAD

**Issue by gilligan** [sanctuary-js/sanctuary#209]
**idea**:
My idea is to record pair programming sessions in which an experienced Sanctuary contributor pairs with a newcomer working on one of the [`good first contribution`](https://github.com/sanctuary-js/sanctuary/labels/good%20first%20contribution) tickets. 

**modus operandi**:
The newcomer would do the coding with the experienced contributor helping out, answering questions.

**purpose**:
On the one hand it is a great learning experience for the person taking part in the pair programming session. On top of that it could be useful for anyone else if the recordings are later made public

**setup**:
The ideal setup for this would probably be a combination of a screen recording tool and [screenhero](https://screenhero.com/) since it is just the best pair programming tool out there afaik - Unfortunately it is OSX only though.

I would be willing to take part in such a session (obviously playing the role of the newcomer). What does everyone think about that?

**Comment by davidchambers** [comment]
I love this idea, Tobias! I look forward to my first pairing session. :)

**Comment by davidchambers** [comment]
I'll close this issue as there's nothing to resolve.

If you're reading this and would like to arrange a pairing session, send me a message on Gitter and we'll find a day and time that suits us both. :)
