### ISSUE TITLE
Add fromJust function to Maybe

### ISSUE THREAD

**Issue by jgoux** [sanctuary-js/sanctuary#228]
Hi,

I often need to extract a value from a Just, and I only dispose of `S.maybe` or `S.fromMaybe` which isn't exactly what I want.

The [Haskell's Data.Maybe](https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Maybe.html) has a `fromJust` function exactly for this purpose.

Could it be possible to add it to Sanctuary ?

**Comment by davidchambers** [comment]
`fromJust` is a partial function, so I'd like to avoid it. We now have [`S.maybeToNullable`][1] which serves a similar role. The other option is to access the `value` property of the Just directly, though this is only safe to do if one first confirms that the value is in fact a Just.

I'm interested to know the situations in which you find yourself dealing with values of type `Maybe a` which you know to be Justs. Could you share a couple of snippets?


[1]: http://sanctuary.js.org/#maybeToNullable

**Comment by jgoux** [comment]
I have a function `queryOne` in my database library which returns a `Maybe a`.

As I execute a postgres sql statement using the `INSERT INTO ... RETURNING` syntax, I'm sure that if the query succeeds I'll have a result.

In fact this is one of the only place where I'd need `fromJust` after searching through my project. xD
So I'll use `S.maybeToNullable` which I wasn't aware of ! :+1: 

Thanks. :100:

**Comment by davidchambers** [comment]
I'm pleased to learn that `S.maybeToNullable` is applicable, and that you only need it in one place. :)
