### ISSUE TITLE
Suggestions for adding more utility methods for Either

### ISSUE THREAD

**Issue by wennergr** [sanctuary-js/sanctuary#230]
First thanks for a good library. 

Needed a few functions on `Either` that I'm used to have. Here below is a list of them. 

More then happy submit a PR if these are features that can be useful for others. 

_Not sure about the policy on `instance` vs (for lack of a better word) `static` functions_

 **Swap the values in an Either (2-complement)**
 `Either#swap :: Either a b ~> Either b a`

 **Return `true` if this either is a right and satisifies a predicate**
 `Either#exists :: Either a b ~> b -> Boolean -> Boolean`

 **Return `true` if this either is a left value or the right value satisfies the given predicate.**
 `Either#forall :: Either a b ~> b -> Boolean -> Boolean`

 **Map on the left side**
 `Either#leftMap :: Either a b ~> (a -> c) -> Either c b`

 **Catamorphism. "fold" on the data constructors (can also exist for Maybe, Future etc...)**
 `Either#cata :: Either a b ~> (a -> c) -> (b -> c) -> c`

 **Run side effect on the right**
 `Either#foreach :: Either a b ~> (b -> ()) -> ()`
 **Or**
 `Either#foreach :: Either a b ~> (b -> ()) -> Either a b`

**Comment by davidchambers** [comment]
> First thanks for a good library.

Thanks! It's a useful stepping stone between Ramda and PureScript. :)

> More then happy submit a PR if these are features that can be useful for others.

Excellent!

> *Not sure about the policy on `instance` vs (for lack of a better word) `static` functions*

The methods are purely for [Fantasy Land][1] compatibility. The idea is that one can use [`R.map`][2], [`R.chain`][3], etc.—and soon their Sanctuary equivalents—rather than invoke methods directly.

> **Swap the values in an Either (2-complement)**
> `Either#swap :: Either a b ~> Either b a`

:thumbsup:

> **Return `true` if this either is a right and satisifies a predicate**
> `Either#exists :: Either a b ~> b -> Boolean -> Boolean`
>
> **Return `true` if this either is a left value or the right value satisfies the given predicate.**
> `Either#forall :: Either a b ~> b -> Boolean -> Boolean`

`b -> Boolean` needs to be parenthesized, I think.

`exists(pred, e)` is sugar for `either(K(false), pred, e)`.

`forall(pred, e)` is sugar for `either(K(true), pred, e)`.

Were we to define these as functions attached to `S`, what might we name them? `exists` and `forall` seem too general. Perhaps these really are more general ideas, though. Could we define something along the lines of `all :: Foldable f => (a -> Boolean) -> f a -> Boolean`?

> **Map on the left side**
> `Either#leftMap :: Either a b ~> (a -> c) -> Either c b`

:thumbsup: We have an issue for this one: #98.

> **Catamorphism. "fold" on the data constructors (can also exist for Maybe, Future etc...)**
> `Either#cata :: Either a b ~> (a -> c) -> (b -> c) -> c`

This looks like [`S.either`][4].

> **Run side effect on the right**
> `Either#foreach :: Either a b ~> (b -> ()) -> ()`
> **Or**
> `Either#foreach :: Either a b ~> (b -> ()) -> Either a b`

Sanctuary currently has no impure functions (or functions intended for impure use). I'd like to keep it that way. We do have `Either#map` as an escape hatch:

```javascript
either.map(console.log)
```


[1]: https://github.com/fantasyland/fantasy-land
[2]: http://ramdajs.com/docs/#map
[3]: http://ramdajs.com/docs/#chain
[4]: http://sanctuary.js.org/#either

**Comment by wennergr** [comment]
> `b -> Boolean` needs to be parenthesized, I think.

Sure, fat fingered :)
> 
> `exists(pred, e)` is sugar for `either(K(false), pred, e)`.
> 
> `forall(pred, e) is sugar for either(K(true), pred, e)`.
> 
> Were we to define these as functions attached to S, what might we name them? exists and forall seem too general. Perhaps these really are more general ideas, though. Could we define something along the lines of `all :: Foldable f => (a -> Boolean) -> f a -> Boolean`?

I picked the `exists` / `forall` keyword because they are usually used to for `existential` and `universal` quantification. 

For a foldable, I like the your idea of `all`. Maybe we can add:
`all :: Foldable f => (a -> Boolean) -> f a -> Boolean`
`any :: Foldable f => (a -> Boolean) -> f a -> Boolean`

Where:
 *  **all** would be folding on the Conjunction monoid (`true`, `and`)
 * **any** would be folding on the Disjunction monoid (`false`, `or`)

**Comment by davidchambers** [comment]
> I picked the `exists` / `forall` keyword because they are usually used for `existential` and `universal` quantification.

This sounds like something I should read about. :)

I really like the idea of `all` and `any`. They're generalized forms of their Ramda namesakes. We could consider defining `none` as well (as sugar for `not(any(pred, foldable))` or `all(complement(pred), foldable)`).

**Comment by wennergr** [comment]
Sounds good. I will hopefully get some time to do a PR later tonight or tomorrow.

My plan was to implement `any`/`all` using `foldMap` + `Conjunction/Disjunction monoid`. I was however surprised to find out that Fantasy land does not consider `foldMap` as a basic building block for a foldable. (Something that I'm used to from Haskell or Scalaz).

Ref: https://hackage.haskell.org/package/base-4.9.0.0/docs/Data-Foldable.html
Ref: https://github.com/scalaz/scalaz/blob/series/7.1.x/core/src/main/scala/scalaz/Foldable.scala#L15

Should we add it?. Another option would be to simply use `Foldable.reduce`

**Comment by davidchambers** [comment]
> Should we add [`foldMap`]?. Another option would be to simply use `Foldable.reduce`

Is the distinction that `foldMap` would allow us to "map" and "reduce" as a single operation?

Going from `(Foldable f, Functor f) => f a` to `(Foldable f, Functor f) => f Boolean` (via `map`) to `Boolean` (via `reduce`) sounds good – `all` and `any` would be compatible with existing data types.

`foldMap` seems useful, though. You could open a Fantasy Land issue for discussion.

**Comment by joneshf** [comment]
> Should we add it?

I'd prefer `foldMap` to `reduce` as the method to implement, to be honest. But there's overhead involved in the change.

> You could open a Fantasy Land issue for discussion.

That's probably the best thing to do.

**Comment by joneshf** [comment]
> Run side effect on the right

That's what `Traversable` is for. Though it's not limited to side-effects. It works with any `Applicative` effects. And since we can encapsulate side-effects as an `Applicative`, we can use `Traversable` stuff to do what you want.

**Comment by jlmorgan** [comment]
Would also like to see something of the following:

(Please forgive my complete understanding of the existing signature syntax:

```javascript
// Returns the first left or a right of all values.
Either.all = collection => find(isLeft, collection) || Either.of(map(get("value"), collection)));

// Return the first right or the first left.
Either.any = collection => find(isRight, collection) || find(isLeft, collection);

// Return an Either from Either or value
Either.from = value => Either.isEither(value) ? value : Either.of(value);

// Tap into Either (or as tapRight/tapLeft)
Either#ifRight = function (f) {
  if (this.isRight() && isFunction(f)) {
    f(this.value);
  }
  return this;
}
Either#ifLeft = function (f) {
  if (this.isLeft() && isFunction(f)) {
    f(this.value);
  }
  return this;
}
```

Same could be applied to `Maybe` et al.

**Comment by davidchambers** [comment]
Let's see what the types of these functions might be, @jlmorgan.

```purescript
Either.all :: Foldable f => f (Either a b) -> Either a (f b)
```

This type seems sound, but I think we could use [`sequence`][1] instead:

```javascript
> Z.sequence(S.Right, [S.Right(1), S.Right(2), S.Right(3)])
Right([1, 2, 3])

> Z.sequence(S.Right, [S.Right(1), S.Right(2), S.Right(3), S.Left('A')])
Left('A')

> Z.sequence(S.Right, [S.Right(1), S.Right(2), S.Right(3), S.Left('A'), S.Left('B')])
Left('A')
```

```purescript
Either.any :: Foldable f => f Any -> Maybe (Either a b)
```

I have several problems with this type. The first is `Any`. According to the Sanctuary philosophy `Array Number` is a useful type but `Array Any` is not. My second concern is the overly specific nature of this function (`S.find(S.is(S.Either))` almost has the desired behaviour). My final concern is that `a` and `b` are unconstrained, limiting our ability to reason about the type of the return value.

```purescript
Either.from :: Any -> Either a b
```

Here is `Any` again. My view is that we should *know* whether or not a value is an either. I also have a strong aversion to special cases (and a less strong aversion to conditional logic in general), so I can't imagine adding this function. The existence of [`is`][2] already makes me slightly queasy.

As for `Either#ifLeft` and `Either#isRight`, `Either#fantasy-land/bimap` (#240) should handle these use cases. As a side note, I see no reason for the `isFunction` checks. ;)


[1]: https://github.com/sanctuary-js/sanctuary-type-classes#sequence
[2]: https://sanctuary.js.org/#is

**Comment by jlmorgan** [comment]
For `Either.any` the collection should be all `Either`s that grabs the first left or the first right in that order. As for the `Either.from`, I see it as a conditional way of ensuring a collection of value are all boxed. I agree that we _should_ know what we have on hand, but it's not enforced until runtime. = \

**Comment by davidchambers** [comment]
> For `Either.any` the collection should be all `Either`s that grabs the first left or the first right in that order.

Ah, I see. So more like this?

```purescript
Either.any :: Foldable f => f (Either a b) -> Maybe (Either a b)
```

What's your use case for this function, out of interest? Also, have you considered this approach?

```javascript
> Z.map(S.head, Z.sequence(S.Right, [S.Right(1), S.Right(2), S.Right(3)]))
Right(Just(1))

> Z.map(S.head, Z.sequence(S.Right, [S.Right(1), S.Right(2), S.Right(3), S.Left('A')]))
Left('A')

> Z.map(S.head, Z.sequence(S.Right, [S.Right(1), S.Right(2), S.Right(3), S.Left('A'), S.Left('B')]))
Left('A')
```

It seems we might already have all the building blocks we need. :)

**Comment by jlmorgan** [comment]
In my mindlessness of home distractions, I miswrote. `Either.any` should be first `Right` or first `Left` not the other way around.

In the case were we have used it is where we read/write from/to multiple channels, but only care if one succeeded.

**Comment by davidchambers** [comment]
I'm closing this issue as it's not actionable. If you're interested in one of the specific functions discussed in this thread, please open a new issue for it.
