### ISSUE TITLE
Applying an Either  in a Pipe throws an error

### ISSUE THREAD

**Issue by rachidbch** [sanctuary-js/sanctuary#247]
Hi as i'm new to sanctuary, i may be missing something obvious but i can't find any reason why those two statements should not give same results:

```js
S.Right(S.inc).ap(S.Right(1)) 
S.pipe([S.Right(S.inc).ap])(S.Right(1)) 
```
first statement gives `Right(2)` as expected but second statement throws following error:

```
/home/rachid/Documents/_PLAY/tagbooks/node_modules/sanctuary-def/index.js:1360
    if (either.isLeft) throw either.value;
                       ^

TypeError: Invalid value

Either#ap :: Either a Function -> Either a b -> Either a c
             ^^^^^^^^^^^^^^^^^
                     1

1)  undefined :: Undefined

The value at position 1 is not a member of ‘Either a Function’.
```
Same behaviour with Maybe/Just instead of Either/Right ...

**Comment by kedashoe** [comment]
Hello @rachidbch, I believe your second expression is losing context. http://goo.gl/CydmDB

**Comment by rachidbch** [comment]
my bad :( Thanks @kedashoe !

**Comment by davidchambers** [comment]
It's worth noting, @rachidbch, that the methods that exist on `S.{Either,Maybe}.prototype` provide [Fantasy Land][1] compatibility. They are not intended to be invoked directly. Instead, they are intended to be invoked by dispatching functions such as [`R.ap`][2] and, soon, [`S.ap`][3].

```javascript
> S.pipe([R.ap(S.Right(S.inc))], S.Right(1))
Right(2)
```


[1]: https://github.com/fantasyland/fantasy-land
[2]: http://ramdajs.com/docs/#ap
[3]: https://github.com/sanctuary-js/sanctuary-type-classes/pull/2

**Comment by rachidbch** [comment]
hey @davidchambers,

Sorry didn't see your comment. Thanks for the good advice.

**Comment by davidchambers** [comment]
You're welcome, @rachidbch. :)
