### ISSUE TITLE
Document required node version in `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by rjmk** [sanctuary-js/sanctuary#248]
The doctest for

```console
> S.encaseEither(S.I, JSON.parse, '[')
Left(new SyntaxError('Unexpected end of input'))
```

will break as `JSON.parse`'s error message changed at some point between node 4 and node 6 to "Unexpected end of JSON input"

We should document which node versions can be used by people developing the library

**Comment by davidchambers** [comment]
How do you feel about this now that #250 has been merged, @rjmk?

**Comment by rjmk** [comment]
Much better solution!
