### ISSUE TITLE
use Yarn

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#265]
npm is a piece of software which is quite possibly beyond repair. [Yarn](https://code.facebook.com/posts/1840075619545360) strikes me as a well-considered, sane piece of software. I :heart: that `yarn` is deterministic, whereas `npm install` can produce different directory structures given different starting states.

I can think of three ways to use Yarn:
- have `make setup` run `npm install yarn` then `yarn`;
- rely on a globally installed `yarn` (as we currently do with `npm`); or
- support `NPM=/path/to/global/yarn make setup`.

Does anyone have a preference for one of these three options?

**Comment by kedashoe** [comment]
Nice! I like option 2, there are many ways a user could install yarn, wouldn't want to presume they prefer `npm install yarn`

**Comment by EvanBurchard** [comment]
+1 for option 2.

**Comment by davidchambers** [comment]
Two votes for option 2 is good enough for me. :)

Just to be clear, none of the options would require Yarn to be installed globally in a certain place. The first option would use npm to install Yarn locally (i.e. at __node_modules/.bin/yarn__). The third option would let the user specify a path to `npm`/`yarn`.

I like option 2, though. I'll see what's involved in getting it to work with CircleCI.

**Comment by davidchambers** [comment]
> I'll see what's involved in getting it to work with CircleCI.

I played around with this but didn't have much luck. I'll revisit this if and when this [feature request][1] becomes a reality.


[1]: https://discuss.circleci.com/t/preinstall-yarn/7353

**Comment by hkrutzer** [comment]
https://yarnpkg.com/en/docs/install-ci didn't work?

**Comment by Avaq** [comment]
It looks like `yarn` is quite similar to [`ied`](https://github.com/alexanderGugel/ied). Ied is a [Nix](https://nixos.org/nix/)-inspired package manager for NodeJS which has worked quite well for me. It seems to have all the same guarantees as `yarn`, and creates a completely flat structure using symlinks. However, it has no support for committing any kind of caches.

**Comment by davidchambers** [comment]
> https://yarnpkg.com/en/docs/install-ci didn't work?

That's right. The problem is that Yarn uses language features only available in recent Node versions:

> ```
> yarn install --no-lockfile
>
> /usr/share/yarn/lib-legacy/constants.js:7
> const userHome = require('user-home');
> ^^^^^
> SyntaxError: Use of const in strict mode.
> ```

We want to run the test suite against several Node versions in parallel. Testing on Node v0.10.x is a low-tech way of ensuring we restrict ourselves to language features supported by all the browsers.

> It looks like `yarn` is quite similar to [`ied`][1].

Thanks for reminding me about ied, Aldwin. I'll take it for a spin! :lollipop:


[1]: https://github.com/alexanderGugel/ied

**Comment by svozza** [comment]
I've now just noticed that a few weeks ago I accidentally edited your post instead of posting mine, David!

**Comment by svozza** [comment]
Just FYI, `yarn` is now installed by default on CircleCI:

https://circleci.com/docs/yarn/

**Comment by davidchambers** [comment]
> I'd be happy to do a PR if that's the route we want to go.

I would like to see this! :)
