### ISSUE TITLE
S.apFirst and S.apSecond

### ISSUE THREAD

**Issue by zhangchiqing** [sanctuary-js/sanctuary#269]
Does it make sense to provide the following two functions?

S.maybeFirst returns the first Maybe value only if both arguments are Just, otherwise return Nothing.

```
S.maybeFirst :: Maybe a -> Maybe b -> Maybe a
> S.maybeFirst(S.Nothing(), S.Nothing())
Nothing()

> S.maybeFirst(S.Just(1), S.Nothing())
Nothing()

> S.maybeFirst(S.Just(1), S.Just('2'))
Just(1)
```

S.maybeSecond returns the second Maybe value only if both arguments are Just, otherwise return Nothing.
```
S.maybeSecond :: Maybe a -> Maybe b -> Maybe b
> S.maybeSecond(S.Nothing(), S.Nothing())
Nothing()

> S.maybeSecond(S.Just(1), S.Nothing())
Nothing()

> S.maybeSecond(S.Just(1), S.Just('2'))
Just('2')
```

Or the above functions can be made by composing existing sanctuary functions? Please advice :)

**Comment by safareli** [comment]
```js
const maybeFirst = first = lift2(a => _ => a)
const maybeSecond = second = lift2(_ => a => a)
```

**Comment by zhangchiqing** [comment]
Thanks for the trick @safareli

**Comment by davidchambers** [comment]
Very nice, @safareli. We can even replace `a => _ => a` with `K`, and `_ => a => a` with `K(I)`:

```javascript
//    maybeFirst :: Maybe a -> Maybe b -> Maybe a
const maybeFirst = S.lift2(S.K);

//    maybeSecond :: Maybe a -> Maybe b -> Maybe b
const maybeSecond = S.lift2(S.K(S.I));
```

**Comment by safareli** [comment]
also they would work on any applicative Either, Future ...

**Comment by joneshf** [comment]
As @safareli points out, `maybeFirst` and `maybeSecond` are `(<*)` and `(*>)` respectively. I don't know if that already exists in the sanctuary ecosystem, but it'd be great to have.

**Comment by scott-christopher** [comment]
> As safareli points out, maybeFirst and maybeSecond are `(<*)` and `(*>)` respectively. I don't know if that already exists in the sanctuary ecosystem, but it'd be great to have.

Only if we can call them `S.icecreamL` and `S.icecreamR`. In all seriousness though, these would be useful additions.

**Comment by davidchambers** [comment]
:icecream:

**Comment by davidchambers** [comment]
Do `(<*)` and `(*>)` go by other names? Valid JavaScript identifiers would be nice. ;)

**Comment by scott-christopher** [comment]
They go by the name of [`applyFirst`](https://pursuit.purescript.org/packages/purescript-prelude/1.1.0/docs/Control.Apply#v:applyFirst) and [`applySecond`](https://pursuit.purescript.org/packages/purescript-prelude/1.1.0/docs/Control.Apply#v:applySecond) in PS, so perhaps `apFirst`/`apSecond` or `apL`/`apR`?

**Comment by davidchambers** [comment]
Thanks, Scott. `apFirst` and `apSecond` sound very good to me. :)

**Comment by safareli** [comment]
apFirst apSecond sounds good, we could also add same for '>>' and '<<' as chain.... Maybe they could be decleared in s-type-classes?

**Comment by zhangchiqing** [comment]
Added in https://github.com/sanctuary-js/sanctuary-type-classes/pull/11
