### ISSUE TITLE
on :: (b -> b -> c) -> (a -> b) -> a -> a -> c

### ISSUE THREAD

**Issue by Bradcomp** [sanctuary-js/sanctuary#281]
While the general `useWith` and `converge` from Ramda aren't very well typed, I do find them to be useful functions.  One of my main use cases for `useWith` is to emulate Haskell's `on` function (this is also known as the psi combinator).

Example:
```javascript
//Point :: {x, y}
const x = prop('x');

//Point -> Point -> Number
const leftmost = on(min, x);
const rightmost = on(max, x); 
```

I struggle with the parameter order for this function. In Haskell it's typically used in infix form:
```haskell
leftmost = min `on` x
```
As a result, I generally define it using the signature above, even though there could be an argument made that the opposite order makes just as much sense.

Is there enough interest for this to be part of Sanctuary?

**Comment by davidchambers** [comment]
> Is there enough interest for this to be part of Sanctuary?

This function seems useful to me. Would you like to submit a pull request?

I think the type signature you provided is missing one `a ->`, by the way.

**Comment by Bradcomp** [comment]
Thanks!  I was missing the `a`.  I will work on a PR.
