### ISSUE TITLE
Add maybe_

### ISSUE THREAD

**Issue by syaiful6** [sanctuary-js/sanctuary#284]
Maybe we need a function with signature:
```
maybe :: (unit -> b) -> (a -> b) -> Maybe a -> b
```
Purescript call this maybe', it helpful if we want to compute the Nothing case lazily.

**Comment by Avaq** [comment]
I've done it like this:

```js
maybe(() => computeNothing(), a => () => computeJust(a), ...)()
```

So essentially you're using an `() -> b`  for `b` in the Maybe signature, making the whole thing "lazy":

```hs
maybe :: (() -> b) -> (a -> () -> b) -> Maybe a -> () -> b
```

**Comment by davidchambers** [comment]
I'd like this function! The only things I'd like to tweak are the name (because we already have a function named [`maybe`][1]) and the type of the first argument:

```purescript
maybe_ :: (() -> b) -> (a -> b) -> Maybe a -> b
```

`() -> b` represents a nullary function.

Would you like to submit a pull request, @syaiful6?


[1]: https://sanctuary.js.org/#maybe

**Comment by syaiful6** [comment]
@davidchambers yup, i will submit it shortly.
