### ISSUE TITLE
Drop Support For Node 0.10

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#292]
Node 0.10 is now [officially unsupported](https://github.com/nodejs/LTS) so I think we should stop testing against it and use the slot freed up to test Node 7. Node 0.12 is EOL in a month's time and I think we should drop support for that too: this will allow us to write our tests in ES6 without involving Babel, the main benefit being string templates which will make testing our error messages _much_ easier.

**Comment by davidchambers** [comment]
Node 0.10 is a decent proxy for oldish browsers. I'd like to keep it in the test matrix for this reason.

> Node 0.12 is EOL in a month's time and I think we should drop support for that too

I agree that we should remove Node 0.12 from the test matrix once it reaches EOL. :thumbsup:

> this will allow us to write our tests in ES6 without involving Babel, the main benefit being string templates which will make testing our error messages *much* easier

Tests for error messages will be removed in #232, as we'll be able to test signatures directly via each function's `toString` method (and the type checking itself is tested in sanctuary-def's test suite).

**Comment by Shard** [comment]
Would it be useful if instead of testing old browsers through Node 0.10 we setup mocha to run tests in the browser and use something like sauce labs to execute the tests as a grid?

I have been doing a bit of work of late integrating mocha tests in the browser so this is something I would be happy to take up.

**Comment by davidchambers** [comment]
That's a wonderful offer, @Shard. Actually running the test suite in browsers is undoubtedly the "correct" approach. My only reservation is that tests of this nature have a reputation for being unreliable, and time-consuming to maintain. Please don't let this deter you, though! :)

**Comment by Shard** [comment]
Yea the effort maintain is something I want to make sure relatively easy as I know it can be quite the pain to debug at times.

I'm planning on moving houses in a couple days so it might take me a couple weeks to have something ready to roll. Ill make sure to report back if there are any major concerns or roadblocks on my end.

**Comment by davidchambers** [comment]
I hope the :house: :truck: :house: goes well, Mark. :)

**Comment by Shard** [comment]
Moving has gone mostly well :tada: , just no line internet until next week :phone:
