### ISSUE TITLE
Add an Equivalent Function to R.path

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#295]
As discussed on Gitter, we should have a companion function to `S.prop`, which fulfils a similar function to [`R.path`](http://ramdajs.com/docs/#path). For internal consistency this function should be named `props`. This would be a good first contribution but if no one has picked it up over the next few days I will submit the PR.

**Comment by tycho01** [comment]
Hm. Ramda also has a `props` function, distinct from its `path` function. Making a `path` equivalent named `props` here would feel confusing to me. :(

**Comment by davidchambers** [comment]
All else being equal, I'm very much in favour of reusing the names used in Ramda and other functional programming libraries and languages. Internal consistency trumps cross-project consistency, though. In #181, for example, we renamed a function which had the same name as its Haskell equivalent for consistency with related Sanctuary functions.
