### ISSUE TITLE
fromMaybe_ :: (() -> a) -> Maybe a -> a

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#296]
We added `maybe_`, a "lazy" version of [`maybe`][1], in #285. `maybe` is a convenient function for situations in which one wants to `map` then apply [`fromMaybe`][2]. It seems to me we should also provide a "lazy" version of `fromMaybe`. Otherwise we'll end up writing `S.maybe_(thunk, S.I, m)` in some cases, which seems a bit strange.

Do you agree?

[1]: https://sanctuary.js.org/#maybe
[2]: https://sanctuary.js.org/#fromMaybe

**Comment by safareli** [comment]
I don't have strong opinion on that, but I would add one suggestion, what if we add type `Thunk` or `Lazy`:
```hs
type Lazy a = () -> a
```
So instead of
```hs
(() -> a) -> Maybe a -> a
```
we would have:
```hs
Lazy a -> Maybe a -> a
```

if we add more functions working with Lazy users could easily find them and also it's more descriptive in type signature.

**Comment by davidchambers** [comment]
I like the idea of `Thunk :: Type -> Type`, @safareli. It should be defined in terms of [`$.Function`][1] to inherit the special handling of function arguments. For example:

```javascript
//    or_ :: (() -> Boolean) -> (() -> Boolean) -> Boolean
const or_ =
def('or_',
    {},
    [$.Function([$.Boolean]), $.Function([$.Boolean]), $.Boolean],
    (f, g) => f() || g());

or_(() => false, () => true);
// => true

or_(() => null, () => true);
// ! TypeError: Invalid value
//
//   or_ :: (() -> Boolean) -> (() -> Boolean) -> Boolean
//                 ^^^^^^^
//                    1
//
//   1)  null :: Null
//
//   The value at position 1 is not a member of ‘Boolean’.
```

If you're interested in pursing this, please open an issue in the sanctuary-def repository to avoid complecting the two proposals. We can easily define `fromMaybe_` using `$.Function([a])` and later change it to `$.Thunk(a)`. :)


[1]: https://github.com/sanctuary-js/sanctuary-def#Function
