### ISSUE TITLE
Browser tests not properly loading modules

### ISSUE THREAD

**Issue by Shard** [sanctuary-js/sanctuary#309]
I noticed some errors when looking at #232 and they seemed to be caused by `sanctuary-def` loading `sanctuary-type-classes` as `undefined` in the browser tests.

I believe it has something to do with browserify configuration, still looking into it.

**Comment by davidchambers** [comment]
Thank you, @Shard. :)

**Comment by davidchambers** [comment]
We fixed this in a straightforward manner in #232:

> ```diff
>  //  dependencies :: Array String
> -var dependencies = Object.keys(require('./package.json').dependencies);
> +var dependencies = ['sanctuary-type-classes', 'sanctuary-def'];
> +
> +eq(dependencies.slice().sort(),
> +   Object.keys(require('./package.json').dependencies).sort());
> ```
