### ISSUE TITLE
sequence in haskell 

### ISSUE THREAD

**Issue by functor-soup** [sanctuary-js/sanctuary#319]
the type signature of sequence in Haskell is 

`sequence :: (Monad m, Traversable t) => t (m a) -> m (t a)`

so I could have `sequence [Left 4, Right 5] => Left 4`

and `sequence [Right 6, Right 9] => Right [6,9]`

Is there an equivalent in sanctuary? I've been scanning libraries that implement the fantasy-land spec, none of them seem to have this (so far)  

Edit : I understand it can be implemented as such (atleast for my task  at hand) 
`x => S.reduce(S.lift2(S.C(S.append)),S.Right([]),x)`, was wondering why something as such is missing

**Comment by davidchambers** [comment]
v0.11.1 provides:

  - [`Maybe#sequence :: Applicative f => Maybe (f a) ~> (a -> f a) -> f (Maybe a)`][1]; and
  - [`Either#sequence :: Applicative f => Either a (f b) ~> (b -> f b) -> f (Either a b)`][2].

[v0.12.0][3] will provide `fantasy-land/traverse` methods instead (for compatibility with version 2 of the Fantasy Land spec) and polymorphic `traverse` and `sequence` functions which wrap [`Z.traverse`][4] and [`Z.sequence`][5] respectively.

Does this answer your question, @functor-soup?


[1]: https://github.com/sanctuary-js/sanctuary/tree/v0.11.1#Maybe.prototype.sequence
[2]: https://github.com/sanctuary-js/sanctuary/tree/v0.11.1#Either.prototype.sequence
[3]: https://github.com/sanctuary-js/sanctuary/issues/255
[4]: https://github.com/sanctuary-js/sanctuary-type-classes#traverse
[5]: https://github.com/sanctuary-js/sanctuary-type-classes#sequence

**Comment by safareli** [comment]
>so I could have sequence [Left 4, Right 5] => Left 4

I think you would get `Left [4]`

**Comment by joneshf** [comment]
```haskell
λ: :t sequenceA [Left 4, Right 5]
sequenceA [Left 4, Right 5] :: (Num a1, Num a) => Either a1 [a]
```

**Comment by functor-soup** [comment]
@davidchambers  Hmm I do remember looking at that for quite some time, thought it was something else. I see I am wrong. How would you use `const b = [S.Left(4), S.Right(5)]` to get `Left(4)` using sanctuary's`sequence`? 

@safareli  I believe @joneshf's comment clarifies that the answer would be `Left 4` because the type signature highlights that pretty clearly

**Comment by safareli** [comment]
@functor-soup correct my mistake

**Comment by davidchambers** [comment]
Here are the Sanctuary equivalents of your Haskell expressions, @functor-soup, on the `dc-fantasy-land` branch:

```javascript
> S.sequence
sequence :: (Applicative f, Traversable t) => TypeRep f -> t (f b) -> f (t b)

> S.sequence(S.Either, [S.Left(4), S.Right(5)])
Left(4)

> S.sequence(S.Either, [S.Right(6), S.Right(9)])
Right([6, 9])
```

I'll close this issue as I believe we've answered your question. :)
