### ISSUE TITLE
Changing R.pipe to S.pipe causes silent failure

### ISSUE THREAD

**Issue by brandones** [sanctuary-js/sanctuary#325]
I'm trying to use Sanctuary within a `Promise.then`.

```
const peek = R.curry((note, value) => {
  console.log('PEEK ', note, value);
  return value;
});

const findIndexAtWordBoundary = R.curry((offset, text) => (
  R.pipe(
    R.slice(offset, Infinity),
    R.findIndex(R.test(/\s/)),
    R.add(offset)
  )(text)
));

client.query('some stuff')
.then(
  R.pipe(
    peek('before'),
    findIndexAtWordBoundary(100),
    peek('after')
  )
)
.catch(() => { throw new Error('augh!'); }
```

Everything works fine when using `R.pipe`, though debugging is a pain, since type errors won't be caught. But if I switch `findIndexAtWordBoundary` to use `S.pipe`, as in

```
const findIndexAtWordBoundary = R.curry((offset, text) => (
  S.pipe(
    R.slice(offset, Infinity),
    R.findIndex(R.test(/\s/)),
    R.add(offset)
  )(text)
));
```

there's a silent failure -- it prints `PEEK  before  (stuff)` but doesn't print `PEEK  after  102` like it does with `R.pipe`. It seems like execution just stops.

**Comment by davidchambers** [comment]
The problem may be that `S.pipe` expects an array of functions whereas `R.pipe` is variadic:

```javascript
> R.pipe(Math.abs, Math.sqrt)(-64)
8

> S.pipe([Math.abs, Math.sqrt], -64)
8
```

If you can avoid using promises I strongly suggest you do so. I imagine the type error being thrown by `S.pipe` is being caught by the complex machinery specified by Promises/A+, resulting in a rejected promise. Consider using a Fantasy Land -compatible data type such as the one provided by [Fluture][1].


[1]: https://github.com/Avaq/Fluture

**Comment by brandones** [comment]
Oh wow. TIL: Promise error handling was spec'd for masochists. Thanks for the help.

**Comment by davidchambers** [comment]
No problem. You're on a good path now. :)
