### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#335]
Now that 0.12 has been released, is it time to formulate a strategy for how we proceed from here? I think it would be great to get a stable version out as soon as is practicable. One place I think we're deficient in is changing the properties in `StrMap`s, i.e., functions such as `assoc`, `evolve` etc. I'm presuming the preferred solution here is lenses and we have an [issue](https://github.com/sanctuary-js/sanctuary/issues/177) for it already but what else needs to be added (or removed) before we're happy to cut 1.0.0?

**Comment by davidchambers** [comment]
These are the changes I'd like to see before v1.0.0:

  - Maybe type moved to a separate project (sanctuary-js/sanctuary-maybe#1);
  - Either type moved to a separate project (sanctuary-js/sanctuary-either#1); and
  - [`create`][1] changed to take `def` as an argument.

Useful functions such as `assoc` can easily be added in minor releases post v1.0.0. v1.0.0 needn't be "complete", but it would be nice for it to at least be clear about how the various Sanctuary projects fit together.


[1]: https://github.com/sanctuary-js/sanctuary/tree/v0.12.0#create

**Comment by svozza** [comment]
Good point regarding `assoc` and friends. My worry about the first two points is that it's mostly out of our hands, we're basically waiting on the outcome of this issue that's been open for months:

https://github.com/fantasyland/fantasy-maybes/issues/8

I hope we're not in danger of falling into to the analysis paralysis that seems to have gripped Ramda.

**Comment by davidchambers** [comment]
> My worry about the first two points is that it's mostly out of our hands

I'm not convinced that moving these projects to the @fantasyland account is the right move, for reasons I will explain (at some point) in fantasyland/fantasy-maybes#8. I think we should go ahead and release sanctuary-maybe and sanctuary-either, *then* decide whether to move the projects. This way we're in control of our own destiny.

> I hope we're not in danger of falling into to the analysis paralysis that seems to have gripped Ramda.

I don't think so. Ramda's governance is too democratic, in my view. I've encouraged Scott to adopt the role of benevolent dictator, but he's unwilling to do so. It's difficult for Ramda to move forward when prominent contributors have conflicting visions of Ramda's future, and significant changes are usually only made unanimously.

**Comment by svozza** [comment]
Ok. That's good to know, I've been holding off on doing any work on splitting out `Either` and `Maybe` because I thought we needed to wait for a decision on moving them; the analysis paralysis I was referring to was on that end rather than here because I figured there would be a lot of conflicting opinions on such a move.

**Comment by svozza** [comment]
Are the Maybe utility functions going to move to the new repo or is it literally just the data type?

**Comment by davidchambers** [comment]
> Are the Maybe utility functions going to move to the new repo or is it literally just the data type?

Just the data type. By keeping the project lean we'll be more likely to encourage others to use it rather than write competing implementations.

**Comment by davidchambers** [comment]
Sanctuary now includes everything I hoped to include in v1.0.0. There will not be a v0.16.0. ;)
