### ISSUE TITLE
Add S.zip and S.zipWith

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#337]
Create a type-safe version of [zip](http://ramdajs.com/0.22.1/docs/#zip) and [zipWith](http://ramdajs.com/0.22.1/docs/#zipWith).

**Comment by davidchambers** [comment]
#222 contains many interesting thoughts on this matter.

**Comment by svozza** [comment]
I'd completely forgotten about that! Guess we should close this then. I still think it's a useful function, I was only using it last week and had to go back to Ramda.

**Comment by davidchambers** [comment]
Let's reopen the discussion. The fact that it's now feasible to use Sanctuary without Ramda may tip the scales in favour of these functions' inclusion.

**Comment by gabejohnson** [comment]
How general do you want to go with this? A quick search of Hoogle shows a lot of `zip` related functions.

**Comment by davidchambers** [comment]
I think it would be okay to provide Array-specific functions:

```haskell
zip :: Array a -> Array b -> Array (Pair a b)
zipWith :: (a -> b -> c) -> Array a -> Array b -> Array c
```

I'm not sure whether it's possible to provide these instead:

```haskell
zip :: Foldable f => f a -> f b -> f (Pair a b)
zipWith :: Foldable f => (a -> b -> c) -> f a -> f b -> f c
```

I imagine this will require more than just Foldable. I haven't given the general form much thought.

**Comment by gabejohnson** [comment]
There's also `zipWithM` to consider.

**Comment by gabejohnson** [comment]
I think `zip` and `zipWith` could work with`String` as well.

**Comment by davidchambers** [comment]
Could you provide an example of applying `zipWith` to strings, @gabejohnson?

**Comment by gabejohnson** [comment]
```js
// zipWith :: (String -> String -> String) -> String -> String -> [String]
joinWith(':', zipWith(a => b => `${a}+${b}`, 'hello', 'world')); // 'h+w:e+o:l+r:l+l:o+d'
```

**Comment by gabejohnson** [comment]
Don't ask me about the utility 😄

**Comment by davidchambers** [comment]
It's a different function, as it's monomorphic (we lost all the type variables). Let's not worry about the String-specific functions. ;)

**Comment by gabejohnson** [comment]
More generally:
```js
// zipWith :: (String -> String -> a) -> String -> String -> [a]
const parseNat = parseInt(10);
sequence(Maybe, zipWith(a => b => lift2(add, parseNat(a), parseNat(b)), '1234', '56789'))
// Just([6, 8, 10, 12])
```

**Comment by gabejohnson** [comment]
@davidchambers I see your point. Was only fixing the type to illustrate.

**Comment by gabejohnson** [comment]
Or more generally:
```js
// zipWith :: (a -> b -> c) -> List a -> List b -> List c
const parseNat = parseInt(10);
sequence(Maybe, zipWith(a => b => lift2(add, parseNat(a), Just(b)), '1234', [5, 6, 7, 8, 9]))
// Just([6, 8, 10, 12])
```

**Comment by safareli** [comment]
you can just apply `toList` to string and feed to `zipWith`
```js
//    toList :: String -> [String]
const toList = s => s.split('')
```

**Comment by masaeedu** [comment]
Similarly, I'd want `zip` for StrMaps. It feels like there's some specialization of functors for which you can generally implement zip. Maybe Traversable?
