### ISSUE TITLE
Add reject and rejectM

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#338]
Add inverse versions of [filter](https://github.com/sanctuary-js/sanctuary#filter--applicativeffoldablefmonoidfa--a-boolean---fa---fa) and [filterM](https://github.com/sanctuary-js/sanctuary#filterm--monadmmonoidma--a-boolean---ma---ma).

**Comment by gabejohnson** [comment]
I'm not sure what you mean by inverse versions. What is the expected behavior?

**Comment by davidchambers** [comment]
I believe the issue title should mention `reject` and `rejectM`, but I'll let Stefano confirm this.

**Comment by svozza** [comment]
Yes, that's it. Apologies, I should have been explicit.

**Comment by gabejohnson** [comment]
Is this necessary since we have `complement`?

**Comment by davidchambers** [comment]
These functions aren't necessary, but they do improve readability in some cases. Consider:

```javascript
> filter(complement(negative), [-2, -1, 0, 1, 2])
[0, 1, 2]

> reject(negative, [-2, -1, 0, 1, 2])
[0, 1, 2]
```

I find myself exerting significantly less effort when reading the second expression.

**Comment by gabejohnson** [comment]
Just playing 😈's advocate.

**Comment by svozza** [comment]
Yeah, I find `complements`too clunky.

**Comment by davidchambers** [comment]
It's worth noting that `complement` is itself unnecessary. This is the desugared form:

```javascript
> filter(map(not, negative), [-2, -1, 0, 1, 2])
[0, 1, 2]
```

Although the `(not, negative)` section actually reads quite nicely, having to reason about lifting `not` makes this much less approachable than the `reject` equivalent.

Put differently, `complement` is nice sugar and `reject` is even nicer sugar in such cases.
