### ISSUE TITLE
Add splitOnRegex 

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#339]
Create a regex version of [splitOn](https://github.com/sanctuary-js/sanctuary#spliton--string---string---arraystring).

**Comment by davidchambers** [comment]
@cust0dian pointed out that [`String#split`][1] has more modes than Vim. Optional capturing groups are problematic:

```javascript
> 'foo;;bar;baz'.split(/;(;)?/)
['foo', ';', 'bar', undefined, 'baz']
```

I see two solutions:

  - __`splitOnRegex :: RegExp -> String -> Array String`__

    This option would ignore capturing groups in the pattern:

    ```javascript
    > splitOnRegex(/;(;)?/, 'foo;;bar;baz')
    ['foo', 'bar', 'baz']
    ```

  - __`splitOnRegex :: RegExp -> String -> { gaps :: Array String, matches :: Array (Array (Maybe String)) }`__

    This option would include an array of arrays of captured substrings in the result:

    ```javascript
    > splitOnRegex(/;(;)?/, 'foo;;bar;baz')
    {gaps: ['foo', 'bar', 'baz'], matches: [[Just(';')], [Nothing]]}
    ```

I favour the first option, as dealing with `Array (Array (Maybe String))` would be annoying.

Regardless of which option we choose we won't be able to use `String#split` in the implementation.

/cc @jordrake


[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split

**Comment by cust0dian** [comment]
I would definitely expect  **`splitOnRegex :: RegExp -> String -> Array String`** (and [Haskell folks seem to agree](http://hackage.haskell.org/package/regex-compat-0.95.1/docs/src/Text-Regex.html#splitRegex)).

If this is left as *good first contribution* and @jordrake isn't up for the challenge, I think we should provide example implementation here since I'm not sure there's a trivial, straightforward one.

**Comment by davidchambers** [comment]
I have a working implementation:

```javascript
function splitOnRegex(pattern, s) {
  //  Create a RegExp object with the `global` flag set, so that
  //  RegExp#exec will advance the `lastIndex` property.
  var $pattern = regex(
    'g' + (pattern.ignoreCase ? 'i' : '') + (pattern.multiline ? 'm' : ''),
    pattern.source
  );
  var result = [];
  var lastIndex = 0;
  var match;
  while ((match = $pattern.exec(s)) != null) {
    //  Handle patterns such as /(?:)/ which match the empty string.
    if ($pattern.lastIndex === lastIndex && match[0] === '') {
      if ($pattern.lastIndex === s.length) return result;
      $pattern.lastIndex += 1;
    } else {
      result.push(s.slice(lastIndex, match.index));
      lastIndex = match.index + match[0].length;
    }
  }
  result.push(s.slice(lastIndex));
  return result;
}
```

Arriving at this version took many iterations. Use a stateless (i.e. non-`global`) RegExp object seemed wise initially, but `'xxx'` would then be split multiple times on `/^x/`. We must provide the whole string each time and rely on the `lastIndex` property of a `global` RegExp object. We even need to manually advance the `lastIndex` property when it gets stuck on a pattern such as `/(?:)/`. It's a complex implementation; we'll need both unit and property-based tests to have confidence in its handling of edge cases.

**Comment by jordrake** [comment]
Happy to change my PR to reflect this. Not sure I could do the unit testing (especially the property-based testing) justice on my first pass but that's what comments are for.

If somebody needs this in sooner, I am equally happy to drop my PR and have somebody more experienced take over.

**Comment by davidchambers** [comment]
There's no rush, @jordrake. Let's continue to iterate on your pull request. :)
