### ISSUE TITLE
Type-class constraints on applied types not handled

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary#346]
I'm not sure if "applied types" is the right term, so I'll just convey the problem by example:

```js
> S.concat(S.Nothing, S.Just(1))
Just(1)

> S.concat(S.Just(1), S.Just(1))
TypeError: Semigroup.methods.concat(...) is not a function
```

This happens because `sanctuary-type-classes` does not have access to the information that `Maybe Number` is not a Semigroup. It only knows that `Maybe` implements `concat`, and therefore must be a Semigroup. The fact that `Maybe#concat` dispatches to `concat` on the inner-type is currently an implementation detail.

**Comment by davidchambers** [comment]
Excellent example. We'd like `Just(1)` to respond "no" when asked whether it satisfies the requirements of Semigroup. Any suggestions as to how it would do so?

**Comment by Avaq** [comment]
I think the way to do it with Fantasy Land, en to ensure that `fantasy-land/concat` only exists on values that are *actually* members of Semigroup. Something like:

```js
function Maybe$concat(other){
  return this.isNothing ?
    other :
    other.isNothing ? this : Just(Z.concat(this.value, other.value));
}; 

function _Maybe(tag, value) {
  this.isNothing = tag === 'Nothing';
  this.isJust = tag === 'Just';
  if (this.isJust) this.value = value;
  if (Z.Semigroup.test(value)) this['fantasy-land/concat'] = Maybe$concat;
}
```

However, that violates another Fantasy Land rule:

> No parts of [the input to `of`] should be checked

**Comment by Avaq** [comment]
The (probably more correct but less convenient) alternative would be to have people define their own Maybe types before they can use them, eg:

```js
const createMaybe = Repr => {
  const Maybe = ...
  if(representsSemigroup(Repr)) Maybe.prorotype['fantasy-land/concat'] = ...
  return Maybe;
}

//...

const MaybeNumber = createMaybe(Number); //Does not create Semigroup members
const MaybeArray = createMaybe(Array); //Creates Semigroup members
```

**Comment by davidchambers** [comment]
> I think the way to do it with Fantasy Land, is to ensure that `fantasy-land/concat` only exists on values that are *actually* members of Semigroup.

This is an ingenious solution, Aldwin! This approach had never occurred to me.

> However, that violates another Fantasy Land rule:
>
> > No parts of [the input to `of`] should be checked
>
> But I have the feeling that this rule was written to prevent a different kind of problem. I'm not sure the case of conditional spec compliance was ever considered.

We would be breaking the letter of the law but not the *spirit* of the law. I'm absolutely fine with this and would go as far as to say that it's a very natural solution to the problem in an object-oriented language as flexible as JavaScript.

Another possibility has just occurred to me. Consider the type signature in question:

```purescript
append :: (Applicative f, Semigroup (f a)) => a -> f a -> f a
```

We could simulate that via:

```javascript
def('append',
    {f: [Z.Applicative, Z.Semigroup], a: [Z.Semigroup]},
    [a, f(a), f(a)],
    append)
```

With some changes to sanctuary-def we could support something like this:

```javascript
def('append',
    {f: [Z.Applicative], f_a: [Z.Semigroup]},
    [a, f(a), f(a)],
    append)
```

Does it make sense to treat `Semigroup (f a)` as shorthand for `(Semigroup f, Semigroup a)`, or am I overlooking some situations in which such an equivalence does not hold?

**Comment by safareli** [comment]
> Does it make sense to treat Semigroup (f a) as shorthand for (Semigroup f, Semigroup a), or am I overlooking some situations in which such an equivalence does not hold?

`List a` is Semigroup for any `a`

**Comment by davidchambers** [comment]
> `List a` is Semigroup for any `a`

Ah, yes, of course!

I thought of another problem with my suggestion: `Identity (Identity Number)`. In this case we need to go down *two* levels to determine the answer. Aldwin's suggestion handles this with ease!
