### ISSUE TITLE
S.filter not checking if second argument implements Monoid

### ISSUE THREAD

**Issue by gabejohnson** [sanctuary-js/sanctuary#361]
When I call:
```js
S.filter(x=>x>2, S.Right(1))
```
I expect to see:
```
Uncaught TypeError: Type-class constraint violation

filter :: (Applicative f, Foldable f, Monoid f) => (a -> Boolean) -> f a -> f a
                                      ^^^^^^^^                       ^^^
                                                                      2

1)  Right(1) :: Either ??? Number, Either ??? FiniteNumber, Either ??? NonZeroFiniteNumber, Either ??? Integer, Either ??? ValidNumber

‘filter’ requires ‘f’ to satisfy the Monoid type-class constraint; the value at position 2 does not.
```
But instead I see:
```
Uncaught TypeError: Cannot read property '1' of null
```

**Comment by gabejohnson** [comment]
This also happens w/ `S.empty`

**Comment by gabejohnson** [comment]
This is a problem with sanctuary-type-classes. Specifically [`getBoundMethod`](https://github.com/sanctuary-js/sanctuary-type-classes/blob/2210d23946472dcecaa21d17a95a88fd4acf1aa0/index.js#L205-L206).

I can fix and submit a PR referencing this issue, or open a new issue there.

**Comment by davidchambers** [comment]
> I can fix and submit a PR referencing this issue

That would be fantastic!

**Comment by gabejohnson** [comment]
Even after submitting the PR. I'd like to keep this open until we bump the version on sanctuary-type-classes and update the dependency.
