### ISSUE TITLE
Multimethod for alt function?

### ISSUE THREAD

**Issue by itrelease** [sanctuary-js/sanctuary#362]
I have a function that basically mimics `if-else-if-else` behavior, but now even if `Just` case already found it still evaluates another branch. So I've thought maybe in `alt` method second argument may be a function that would be called only if first argument is `Nothing`? Or maybe there are already exists way for doing what I want?

```
const keywords = {
  path: {
    ...
  },
  lang: {
    ...
  }
};

function getKeywords(req, lang, document) {
  return S.pipe([
    S.toMaybe,
    S.alt(
      S.__,
      S.toMaybe(keywords.path[req.path]) // if this will be a function like () => S.toMaybe(keywords.path[req.path])
    ),
    S.alt(
      S.__,
      S.toMaybe(keywords.lang[lang]) // and this also
    )
  ])(get(document, 'root.keywords'));
}
```

**Comment by davidchambers** [comment]
Does [`maybe_`][1] provide the functionality you desire, @itrelease? You can provide [`I`][2] as the second argument if you don't want to transform the value inside a Just.


[1]: https://sanctuary.js.org/#maybe_
[2]: https://sanctuary.js.org/#I

**Comment by itrelease** [comment]
@davidchambers that'll work, thanks for pointing to `maybe_` method

**Comment by davidchambers** [comment]
No problem. :)
