### ISSUE TITLE
Compared to Folktale?

### ISSUE THREAD

**Issue by jmatsushita** [sanctuary-js/sanctuary#366]
Hi there,

It would be quite interesting to hear what are some of the ways that Folktale and Sanctuary differ and compare in their approaches, as well as how they can interoperate (as hinted [here](https://github.com/sanctuary-js/sanctuary/issues/210#issuecomment-217225168))

Thanks!

Jun

**Comment by jmatsushita** [comment]
Seems that for Flutures there's a benchmark comparing with Folktale's data.task https://github.com/fluture-js/Fluture#benchmarks

**Comment by davidchambers** [comment]
One could describe Folktale as Scala-flavoured whereas Sanctuary is Haskell-flavoured. It would be helpful to mention Folktale in the documentation and to highlight the significant differences between Folktale and Sanctuary.

**Comment by danielo515** [comment]
Are you going to add it to the docs then?

**Comment by davidchambers** [comment]
> Are you going to add it to the docs then?

Yep! See #571. :)
