### ISSUE TITLE
Add R.nth equivalent

### ISSUE THREAD

**Issue by Jacse** [sanctuary-js/sanctuary#374]
Would be great to a safe alternative to [Ramdas `R.nth`](http://ramdajs.com/docs/#nth).
Should be able to submit a PR soon if there are no objections.

**Comment by Jacse** [comment]
Oh jees we have S.at. So sorry

**Comment by davidchambers** [comment]
No problem. I don't recall why we chose a different name for this function.

**Comment by Levino** [comment]
Where did `S.at` go? It seems to have been removed...
