### ISSUE TITLE
S.pipe advanced type checking.

### ISSUE THREAD

**Issue by JAForbes** [sanctuary-js/sanctuary#383]
I believe sanctuary should be able to inform us of invalid compositions before we apply the composition with a value.

E.g.

```js
S.pipe([S.find, S.find])
```

The above shouldn't "compile" because `S.find` expects an `Array specifically, but instead will receive a `Maybe`.  But currently the above code will only fail when we apply a value to the above composition.

It should theoretically be possible to throw a type error at definition time.  Without a value we should still have enough information to determine a type error should occur.

Since fantasy land has moved to prefixing, we are likely going to be using `pipe` more and more often and this potentially gives us more power to do early type checking.

I believe it would require `pipe` sniffing for sanctuary-def functions, and determining incompatibilities.  

It may not be possible to definitively declare all compositions are incompatible, but there may at least be a subset where we can definitively determine that without requiring a value.

I can see a few problems with this idea, but hopefully someone else may see a path.
In any case I think its worthy of discussion.  Any thoughts?

**Comment by davidchambers** [comment]
The problem, James, is that `S.pipe` is currently defined like so:

```javascript
S.pipe = def('pipe', {}, [$.Array($.AnyFunction), a, b], pipe);
```

`S.pipe` is the one function in the library that isn't well typed. I'm willing to live with this as it's such a useful function, and fixed-arity functions (`S.pipe2`, `S.pipe3`, etc.) would be frustrating.

The internal `pipe` function doesn't receive the array of functions until *both* arguments have been provided, so having `pipe` interrogate the functions in advance is not an option.

I'm willing to put this in the too hard basket.

**Comment by ivenmarquardt** [comment]
This is indeed a hard problem, because you would have to provide a proper unification algorithm to determine the (intermediate) types of partially applied functions. I've been working on this for a couple of months now and am still in a steep learning curve. If you're interested you can get an idea at [ftor](https://github.com/kongware/ftor).
