### ISSUE TITLE
partition :: (a -> Boolean) -> Array a -> Pair (Array a) (Array a)

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#385]
Haskell provides [`partition`][1] in Data.List, but it's just one of many [`partition`][2] functions. Can we generalize? The first step might be to accept any Foldable:

```haskell
partition :: Foldable f => (a -> Boolean) -> f a -> Pair (Array a) (Array a)
```

Could we go one step further by parameterizing `Array` in the return type? Would adding a Monoid constraint to `f` be sufficient?

[1]: http://hackage.haskell.org/package/base-4.9.1.0/docs/Data-List.html#v:partition
[2]: https://www.haskell.org/hoogle/?hoogle=partition

**Comment by gabejohnson** [comment]
Can you give some examples of the behavior under different `Foldable` and `Monoid` combinations?

**Comment by gabejohnson** [comment]
Nevermind. I just looked at the second link. Sounds good to me!

**Comment by davidchambers** [comment]
I was imagining something like this:

```javascript
> S.partition(S.odd, [1, 2, 3])
[[1, 3], [2]]

> S.partition(S.odd, Cons(1, Cons(2, Cons(3, Nil))))
[Cons(1, Cons(3, Nil)), Cons(2, Nil)]
```

Does this seem reasonable?

**Comment by safareli** [comment]
``` purescript 
a :: (Monoid m, Foldable f)
  => (a -> Boolean) -> (a -> m) -> f a -> Pair m m
  
c :: (Monoid m, Monoid m', Foldable f)
  => (a -> Boolean) -> (a -> m) ->  (a -> m') -> f a -> Pair m m'
  
c :: (Monoid m, Monoid m',  Foldable f)
  => (a -> Either m m') -> f a -> Pair m m'
  
d :: (Monoid m,  Foldable f)
  => (a -> Either m m) -> f a -> Pair m m
  ```


I think `c` is best from this 4.

If we go farther [`These`](https://hackage.haskell.org/package/these-0.7.3/docs/Data-These.html) type could be used instead of `Either`. it will allow to either return `m'` or `m` or both `m` and `m'`. with this one could for example accumulate Min and Max in one fold this way:
``` js 
// in this case  -- partition :: (Int -> These Min Max) -> List Int -> Pair Min Max
partition(a => These(Min(a), Max(b)), as)
```

**Comment by davidchambers** [comment]
@safareli, could you show how one would partition `[1, 2, 3]` into `[[1, 3], [2]]` using each of these functions? The type signatures are very helpful, but don't highlight the trade-offs that may exist between generality and convenience.

**Comment by gabejohnson** [comment]
@safareli `These` is very interesting. If we had it I think it would make a better return type for `tagBy` as it captures the semantics of choice. `Either` discriminates between `Left` and `Right`.

**Comment by safareli** [comment]
`These` wouldn't be that useful for `tagBy` as you will never use `These a b` variant of the type.

**Comment by safareli** [comment]
```js
// partition :: (Int -> These (Set Int) (Set Int)) -> [Int] -> Pair (Set Int) (Set Int)
// -- in this case either would also be enough but in the Min Max example it's not
partition(a => (isEven(a) ? This: That)(Set.of(a)), as)
```

**Comment by gabejohnson** [comment]
Ahhh...we want `tagBy` to be exclusive.
