### ISSUE TITLE
Dispatch to 'sanctuary' prefixed methods

### ISSUE THREAD

**Issue by gabejohnson** [sanctuary-js/sanctuary#392]
As suggested in @kedashoe's comment https://github.com/sanctuary-js/sanctuary-type-classes/pull/50#issuecomment-299247292, I propose that Sanctuary dispatch to prefixed methods where appropriate.

Currently, Sanctuary derives many of it's functions from Fantasy Land methods. This is great as it allows tons of functionality from the minimal implementations laid out in the spec. But there can be a cost in efficiency.

Library authors that try to interoperate well with Sanctuary may wish to use more efficient algorithms when implementing Sanctuary functions that are currently derived. I think we should help them out in this endeavor.

```js
const Nil = {
  head: function head() {
    return this;
  },
  tail: function tail() {
    return this;
  },
  cons: function cons(x) {
    return new Pair(x, this);
  },
  filter: function filter(pred) {
    return this;
  }
};
Nil['sanctuary/head'] = Nil.head;
Nil['sanctuary/tail'] = Nil.tail;
Nil['sanctuary/prepend'] = Nil.cons;
Nil['sanctuary/filter'] = Nil.filter;
Object.freeze(Nil);

function Pair(car, cdr) {
  this.car = car;
  this.cdr = cdr;
}
Pair.prototype.head = Pair.prototype['sanctuary/head'] = function head() {
  return this.car;
}
Pair.prototype.tail = Pair.prototype['sanctuary/tail'] = function tail() {
  return this.cdr;
}
Pair.prototype.cons = Pair.prototype['sanctuary/prepend'] = function cons(x) {
  return new Pair(x, this.car);
}
Pair.prototype.filter = Pair.prototype['sanctuary/filter'] = function filter(pred) {
  var newCdr = this.cdr.filter(pred);
  return pred(this.car) ? new Pair(this.car, newCdr) : newCdr;
}
```

This proposal could also serve some of Sanctuary's own data structure implementations, such as sanctuary-set and sanctuary-map.

Dispatching to prefixed methods could also allow sanctuary-type-classes to provide reference implementations of prospective FL algebras.

An alternative is to add adjunct methods to the FL spec such as `apFirst`, `apSecond`, `join`, Kleisli composition, etc.

**Comment by davidchambers** [comment]
Let's tease this apart. I see three groups which could leverage `sanctuary/`-prefixed methods:

1.  Functions such as [`S.head`][1] without type-class constraints and thus without defined laws. Dispatching in such cases would give us ad hoc polymorphism.

2.  Functions such as [`S.join`][2] with type-class constrains which thus obey the associated laws. Dispatching in such cases would allow for more efficient implementations.

3.  Functions such as [`S.filter`][3] with overly restrictive type-class constraints which are thus limited in the types upon which they can operate. The Pair type above is incompatible with `S.filter`, but could be compatible with a new version of `S.filter` with a `Filterable f =>` constraint.

My initial thoughts are as follows:

1.  I'm not sure ad hoc polymorphism is desirable. If an idea really is general it should be possible to define laws for it. That said, I would love to remove the [List][4] type! I'd be happy to say that `S.head` dispatches to `sanctuary/head` and that implementations are provided for Array and String.

2.  I'm very much in favour of allowing these efficient implementations. I believe the right place to document these methods is in the Fantasy Land spec as you suggested. :)

3.  I'm very much opposed to adding ad hoc dispatching to principled functions such as `S.filter`. I don't think Sanctuary should include functions which can operate on values which do not satisfy the documented type-class constraints. Instead, I would like to see additions to the Fantasy Land spec to generalize functions such as `S.filter` (fantasyland/fantasy-land#33).


[1]: https://sanctuary.js.org/#head
[2]: https://sanctuary.js.org/#join
[3]: https://sanctuary.js.org/#filter
[4]: https://sanctuary.js.org/#list

**Comment by kedashoe** [comment]
Nice breakdown @davidchambers , thank you for your thoughts on it.

**Comment by gabejohnson** [comment]
I can't counter any of your arguments David. 😄

**Comment by davidchambers** [comment]
I remain open to the possibility of dispatching to `sanctuary/`-prefixed methods, but only to support operations which are considered too specific for Fantasy Land (`head` may be in this category).

I'll close this issue, as it requires no action.
