### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by arsaniwilliam** [sanctuary-js/sanctuary#394]
The package in npm has not been updated in about 3 months.. I was wondering if there was a schedule for new releases published to npm.
Thank you for all your great work people! Keep it up!!

**Comment by Avaq** [comment]
According to [a recent comment](https://gitter.im/sanctuary-js/sanctuary?at=591799fe83cb5db0732b1f22) by @davidchambers on Gitter, we are very close:

<pre>
                                o <--- <a href="https://github.com/sanctuary-js/sanctuary/pull/388">sanctuary#388</a>
                               / \     (sanctuary-type-classes@5.0.0)
                              /   \
                             /     \
         <a href="https://github.com/sanctuary-js/sanctuary/pull/365">sanctuary#365</a> ---> o       o <--- <a href="https://github.com/sanctuary-js/sanctuary/pull/389">sanctuary#389</a>
   (sortBy for Arrays)       \      |      (array: generalize S.find)
                              \     |
                               \    |
                                \   |   o <--- tweaks!
                                 \  |  /
                                  \ | /
                                   \|/
                                    o <--- Release sanctuary@0.13.0
</pre>

**Comment by davidchambers** [comment]
Thanks for posting that, Aldwin. As you can see, Arsani, we are very close! :)

**Comment by arsaniwilliam** [comment]
That's good to know. Thank you!
