### ISSUE TITLE
San Francisco gathering

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#398]
I'll be in San Francisco the week of 5 June – 9 June. It would be fun to get together with a few of you nice people from the Sanctuary community while I'm in the Bay Area. I'm imagining a few drinks one evening at a quiet bar. If you're interested in getting together, respond in this thread or privately via Gitter or email.

:beers:

**Comment by gabejohnson** [comment]
> I'll be in San Francisco the week of 5 May – 9 May
I don't have a time machine 😄 . But I live in a flyover state anyway. Have fun!

**Comment by davidchambers** [comment]
I can't believe it's almost June! Thanks for the correction, Gabe. :)
