### ISSUE TITLE
remove functions which take uncurried functions

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#416]
We have several functions which take uncurried functions as arguments:

```console
$ grep '//# .*_ :: .*,' index.js
  //# reduce_ :: Foldable f => ((b, a) -> b) -> b -> f a -> b
  //# flip_ :: ((a, b) -> c) -> b -> a -> c
  //# on_ :: ((b, b) -> c) -> (a -> b) -> a -> a -> c
  //# encase2_ :: ((a, b) -> c) -> a -> b -> Maybe c
  //# encase3_ :: ((a, b, c) -> d) -> a -> b -> c -> Maybe d
  //# encaseEither2_ :: (Error -> l) -> ((a, b) -> r) -> a -> b -> Either l r
  //# encaseEither3_ :: (Error -> l) -> ((a, b, c) -> r) -> a -> b -> c -> Either l r
  //# groupBy_ :: ((a, a) -> Boolean) -> Array a -> Array (Array a)
```

Thanks to #289 we now have [`curry2`][1], [`curry3`][2], [`curry4`][3], and [`curry5`][4]. These provide a way to make uncurried functions compatible with functions such as [`encase2`][5] which require a *curried* function:

```javascript
S.encase2(S.curry2(f)) = S.encase2_(f)
```

We could remove all the `_`-suffixed functions listed above. Not only would this provide a small simplification now, it would save us from adding similar `_`-suffixed functions in future. Thoughts?

[1]: https://github.com/sanctuary-js/sanctuary/tree/v0.13.2#curry2
[2]: https://github.com/sanctuary-js/sanctuary/tree/v0.13.2#curry3
[3]: https://github.com/sanctuary-js/sanctuary/tree/v0.13.2#curry4
[4]: https://github.com/sanctuary-js/sanctuary/tree/v0.13.2#curry5
[5]: https://github.com/sanctuary-js/sanctuary/tree/v0.13.2#encase2

**Comment by davidchambers** [comment]
@JAForbes, @rjmk, @svozza: Any objections?

**Comment by rjmk** [comment]
No objections.

Does this cut off a possible route of optimisations for a user of Sanctuary? i.e. using js functions with no closures or indirection in cases where that's useful

**Comment by davidchambers** [comment]
> Does this cut off a possible route of optimisations for a user of Sanctuary?

Yes, it does. Currently `S.reduce_(S.add, 0)` is more efficient than `S.reduce(S.add, 0)` because it avoids unnecessarily using `uncurry2` to wrap `S.add` before passing it to `Z.reduce`.

[Empathy for the Machine][1] is a trait shared by many programmers. I believe that in many cases it's a liability rather than an asset. Performance is sometimes very important, but we tend to consider it—and make concessions to it—even when it's unimportant.

I don't like the idea of some Sanctuary users having a mental note to _use `S.reduce_` if possible, as `S.reduce` is slower_. I'd prefer to provide just one option (in accordance with the _Zen of Python_).


[1]: http://atp.fm/episodes/115

**Comment by JAForbes** [comment]
Is the performance penalty significant?

-----Original Message-----

**Comment by davidchambers** [comment]
> Is the performance penalty significant?

I'll let you decide:

```
> var S = require('sanctuary')
> function time(thunk) { console.time(''); thunk(); console.timeEnd(''); }
> time(function() { S.reduce(S.add, 0, S.range(0, 5000)); })
: 1113.919ms
> time(function() { S.reduce_(S.add, 0, S.range(0, 5000)); })
: 1664.283ms
> time(function() { S.reduce(function(x) { return function(y) { return x + y; }; }, 0, S.range(0, 5000)); })
: 1045.408ms
> time(function() { S.reduce_(function(x, y) { return x + y; }, 0, S.range(0, 5000)); })
: 1613.222ms
> var S_ = S.create({checkTypes: false, env: []})
> time(function() { S_.reduce(S_.add, 0, S_.range(0, 5000)); })
: 16.418ms
> time(function() { S_.reduce_(S_.add, 0, S_.range(0, 5000)); })
: 3.827ms
> time(function() { S_.reduce(function(x) { return function(y) { return x + y; }; }, 0, S_.range(0, 5000)); })
: 1.372ms
> time(function() { S_.reduce_(function(x, y) { return x + y; }, 0, S_.range(0, 5000)); })
: 0.859ms
```

I'm sure we can all agree that type checking is the real source of slowness. ;)

**Comment by Avaq** [comment]
I think if you need to optimize a code path for performance, you will use `Z` directly, or even functions specialized for your data type. I see no reason to keep the "non-curried-function-taking functions" around for performance reasons, as I would avoid even those when optimizing.

**Comment by JAForbes** [comment]
Interesting.  Yeah type checking is definitely taking the most time.

> time(function() { S_.reduce(S_.add, 0, S_.range(0, 5000)); })
: 16.418ms
> time(function() { S_.reduce_(S_.add, 0, S_.range(0, 5000)); })
: 3.827ms

This jumps out to me as a meaningful difference for UI programming, typically a frame is 16ms, but we can really only spend ~12ms of that frame for JS to run.  The curried example would not fit in a frame, the uncurried one would.

I am pretty stunned currying makes that much of difference even for just summing a list of 5000 items.  Micro benchmarks should always be treated with scepticism, but I'd expect that to take a lot less time.

I don't necessarily have objections because if you have a hot code path, you probably should use a for loop to sum a list of numbers instead of sanctuary.  And... I've never used the uncurried versions.  But I am surprised currying alone, without type checking takes that much of a toll.  

For reference, in ramda, currying doesn't have the same impact:

```js
function time(thunk) { console.time(''); thunk(); console.timeEnd(''); }

time(function(){
  reduce(add, 0, range(0, 5000))
})
// 2.31ms
```

I don't know why currying in sanctuary without type checking takes 16ms, but only ~2ms for ramda.  Is Sanctuary's curry method doing more work than ramda's even with type checking off?

**Comment by davidchambers** [comment]
> Is Sanctuary's curry method doing more work than ramda's even with type checking off?

Yes. It defines [`inspect`/`toString`][1]. Also, it checks `opts.checkTypes` in several places to decide whether to perform type checking. It would be interesting to profile our internal `curry` function in order to better understand why it is slower than the Ramda equivalent.


[1]: https://github.com/sanctuary-js/sanctuary-def/blob/v0.12.1/index.js#L2431-L2452

**Comment by JAForbes** [comment]
> Yes. It defines inspect/toString. Also, it checks opts.checkTypes in several places to decide whether to perform type checking. 

I don't imagine inspect/toString would have a cost on execution.  It would be interesting to explore this further.  That's a significant performance difference.  Maybe it's worth while to export separate curry functions depending on `typeCheck`'s value?

It might even be helpful to disable custom inspect/toString for production, as they are really are just a development convenience (but only if they have any impact on performance).
