### ISSUE TITLE
Undetected garbage input for traverse

### ISSUE THREAD

**Issue by Avaq** [sanctuary-js/sanctuary#417]
![latest-screenshot](https://user-images.githubusercontent.com/1217745/27372676-aa049a58-5665-11e7-8529-65a510882797.png)

---

If I understand the problem correctly, then I think all functions which take a `TypeRep f` and an `f` somewhere would suffer from the same problem. I fear the solution would involve adding a new kind of check to sanctuary-def, or in other words: built-in support for type representatives.

**Comment by Avaq** [comment]
Oh it's worse. In your example we cannot know that `Maybe` is the wrong typerep, unless we would know the return type of `words` beforehand.

**Comment by davidchambers** [comment]
We don't know a function's return type at run time, so I don't think there's anything sanctuary-def can do in this case, unfortunately.
