### ISSUE TITLE
Update docs (reminder)

### ISSUE THREAD

**Issue by nikolal** [sanctuary-js/sanctuary#419]
Reminder to update docs with recommendations for new users.
Based on this comment:

https://github.com/ramda/ramda-fantasy/issues/157#issuecomment-292780227

**Comment by davidchambers** [comment]
[sanctuary-maybe][1] and [sanctuary-either][2] have been released and include documentation, so I'll close this issue. If I misunderstood its purpose, @nikolal, please correct me.


[1]: https://github.com/sanctuary-js/sanctuary-maybe
[2]: https://github.com/sanctuary-js/sanctuary-either
