### ISSUE TITLE
Should docs reflect that Maybe type satisfies Ord spec?

### ISSUE THREAD

**Issue by 1ven** [sanctuary-js/sanctuary#421]
Currently [maybe doc](https://sanctuary.js.org/#maybe-type) is not saying that maybe implements Ord spec, but it has `.lte` [method](https://sanctuary.js.org/#Maybe.prototype.fantasy-land/lte).

**Comment by davidchambers** [comment]
Good catch. Would you like to open a pull request to correct this? If so, please also update the documentation for the Either type.

**Comment by 1ven** [comment]
@davidchambers [done](https://github.com/sanctuary-js/sanctuary/pull/422)
Replaced `Setoid` by `Ord` spec.

**Comment by davidchambers** [comment]
Fixed in #422.
