### ISSUE TITLE
Implicit arguments

### ISSUE THREAD

**Issue by samueller** [sanctuary-js/sanctuary#426]
The Sanctuary documentation states:
> In x.map(y), for example, the map method takes an implicit argument x in addition to the explicit argument y. The type of the value upon which a method is invoked appears at the beginning of the signature, separated from the arguments and return value by a squiggly arrow (~>). The type of the map method of the Maybe type is written Maybe a ~> (a -> b) -> Maybe b.

But when I try to access the `map` function on a `Maybe`, I get undefined:
```javascript
> S.Just(1).map
undefined
> S.Just(1).map(x => x)
TypeError: S.Just(...).map is not a function
    at repl:1:11
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:544:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```
The same issue occurs with any of the Sanctuary functions I tried with the squiggly arrow `~>` in its type signature. Did I not understand this implicit argument mechanism properly?

**Comment by davidchambers** [comment]
The documentation is misleading. It should refer to _the `fantasy-land/map` method_ rather than _the `map` method_. A pull request to fix this would be appreciated. :)

It's worth mentioning that it's idiomatic to use `S.map` rather than invoking `fantasy-land/map` methods directly.

**Comment by samueller** [comment]
Ok, I think I understand everything now. So this works:
```javascript
> S.Just(1)['fantasy-land/map'](x => x + 1)
Just(2)
```
I didn't realize that `Maybe#fantasy-land/map` meant the method name was actually `fantasy-land/map`. I'm happy to do a pull request to update the example code to reflect this.

**Comment by davidchambers** [comment]
I believe all we need to do is replace two occurrences of `map` with `fantasy-land/map`. The `x.map(y)` example is fine as it's just a hypothetical example.

**Comment by samueller** [comment]
I agree with the existing `map` examples being fine, with `fantasy-land/map` used instead of `map`. So I'd replace this:
```javascript
> S.map(Math.sqrt, S.Nothing)
Nothing

> S.map(Math.sqrt, S.Just(9))
Just(3)
```
with this:
```javascript
> S.Nothing['fantasy-land/map'](Math.sqrt)
Nothing

> S.Just(9)['fantasy-land/map'](Math.sqrt)
Just(3)
```
Does it make sense for me to update the rest of the fantasy-land methods as well?

**Comment by gabejohnson** [comment]
@samueller the example from the "Types" section is very different in intent from the examples in the rest of the documentation.

Sanctuary (through sanctuary-type-classes) dispatches to the `fantasy-land` namespaces methods. It is not intended that types provided by Sanctuary be called in this manner.

So long story short, there's no need to change the rest of the examples.

**Comment by davidchambers** [comment]
I agree with Gabe. Mentioning `fantasy-land/map` in the usage examples could prevent some users from discovering `S.map`.

**Comment by samueller** [comment]
The update to the Types section of the documentation helps. The usage examples in the documentation for the fantasy-land functions are still a bit confusing for people new to Sanctuary. We're starting to teach kids Sanctuary as part of a functional-first JavaScript curriculum. So we're very sensitive to this kind of thing.

Maybe a disclaimer above the usage examples would help, something along the lines of this?
> It is idiomatic to use the [`map`](https://sanctuary.js.org/#map) function instead of `fantasy-land/map`, like this:

**Comment by Avaq** [comment]
> We're starting to teach kids Sanctuary

That sounds amazing! :clap:
