### ISSUE TITLE
question about Maybe 

### ISSUE THREAD

**Issue by jgranduel** [sanctuary-js/sanctuary#427]
Hi, 

as a functional JS and fantasy-land specs and many implementations newcomer, I recently read this post about Maybe usage (https://oliverjash.me/2017/04/10/why-use-a-maybe-type-in-javascript). Maybe is imported from folktale.

```javascript
> Maybe = require("folktale/maybe") //folktale-2.0.0
> const users = [{ id: 1, name: 'Bob' }, { id: 2, name: 'Saffron' }]
> Maybe.fromNullable( users.find( u => u.id === 5))
folktale:Maybe.Nothing({  })
>Maybe.fromNullable( users.find( u => u.id === 5)).getOrElse('')
''
```
Ramda-fantasy would just be  ```RF.Maybe( users.find( u => u.id === 5))```, I think.

What would be the equivalent with Sanctuary (using S, $, Z if needed for better practices) ?
Thanks

**Comment by davidchambers** [comment]
Here are the Sanctuary equivalents:

```javascript
> S.find(r => r.id === 5, [{id: 1, name: 'Bob'}, {id: 2, name: 'Saffron'}])
Nothing

> S.fromMaybe({id: NaN, name: ''}, S.find(r => r.id === 5, [{id: 1, name: 'Bob'}, {id: 2, name: 'Saffron'}]))
{id: NaN, name: ''}
```

Note that [`S.find`][1] is more precise than `Array#find` because it tells us unambiguously whether a match was found (whereas `[undefined].find(_ => true)` and `[undefined].find(_ => false)` both evaluate to `undefined`).


[1]: https://sanctuary.js.org/#find

**Comment by jgranduel** [comment]
Thanks a lot! I wasn't searching in the right direction...
Best regards.

**Comment by davidchambers** [comment]
I'm happy to help. Feel free to ask questions on [Gitter][1] in future if that's convenient for you.


[1]: https://gitter.im/sanctuary-js/sanctuary
