### ISSUE TITLE
Add insert for Objects

### ISSUE THREAD

**Issue by ucodescott** [sanctuary-js/sanctuary#434]
Would be great to have an `insert` function similar to [Ramda's `assoc`](http://ramdajs.com/docs/#assoc). I like the name `insert` better as that seems more clear when working with other dictionary APIs ([Elm](http://package.elm-lang.org/packages/elm-lang/core/latest/Dict#insert) and [Haskell](http://hackage.haskell.org/package/containers-0.5.10.2/docs/Data-Map-Lazy.html#v:insert)).

The type signature might be something like:
```haskell
insert :: String -> Any -> Object -> Object
```

An implementation might look like the following:
```javascript
function insert(key, value, object) {
	var newEntry = {};
	newEntry[key] = value;
	return Object.assign(newEntry, object);
}
S.insert = def(‘insert’, {}, [$.String, $.Any, $.Object, $.Object], insert);
```

If an insert function makes sense for Sanctuary, I'm happy to create a pull request.

**Comment by Avaq** [comment]
Should `insert` operate on `StrMap` rather than `Object`?

```sh
insert :: String -> a -> StrMap a -> StrMap a
```

**Comment by davidchambers** [comment]
I'm very much in favour of this addition. I agree with @Avaq that we should stick to a strict type.

**Comment by samueller** [comment]
I like `StrMap`, surprised I missed that from the existing Object functions. Seems like the implementation I wrote above would still work.

**Comment by davidchambers** [comment]
> Seems like the implementation I wrote above would still work.

It would, although we try to stick to ES5 language features and APIs to support lots of environments without polyfills.

I'd love to see a pull request, Scott. :)

**Comment by davidchambers** [comment]
We could utilize `Z.concat` to avoid making decisions about inherited properties:

```javascript
function insert(key, val, obj) {
  var result = Z.concat(obj, {});
  result[key] = val;
  return result;
}
```

**Comment by samueller** [comment]
BTW, @ucodescott is me. I accidentally created this issue under the GitHub account I use to teach others with. But GitHub wouldn't let me edit the account or delete the issue... Didn't want anyone to think I hijacked this issue from someone else :).

**Comment by masaeedu** [comment]
Would this be identical to `const insert = k => v => S.concat({ [k]: v })`? Maybe having a separate `k => v => { [k]: v }` primitive as well would be useful. This can then be composed with `concat`.

**Comment by davidchambers** [comment]
Good idea, @masaeedu. We could name the function `singleton`. What do you think? Would you like to submit a pull request?

**Comment by davidchambers** [comment]
Added in #435.
