### ISSUE TITLE
Performance issue on iOS

### ISSUE THREAD

**Issue by dakom** [sanctuary-js/sanctuary#444]
*EDIT* - I've now put together a public repo for better isolated testing and comparison to Ramda. I'll leave the below in, just in case it sheds any more light on the issue, but the _temporary_ test repo is at: 

https://github.com/dakom/temp-sanctuary-test

This publishes a live demo at https://dakom.github.io/temp-sanctuary-test/

When I point my ipad at the live demo, the difference between Ramda and Sanctuary averages somewhere around 75ms (with a larger gap at warmup). On desktop there is also a large gap but not as severe (around 20ms - still, more than a full frame).

-------
I ran into a performance issue on iOS when using `S.chain()`. I'm not completely sure if it's the ultimate culprit, but it seems to me that `S.chain()` called a few times in a row adds ~15-25ms to the execution. It may or may not be worse when combined with `S.pipe()`, but `S.pipe()` by itself seems fine.

Please consider the following data taken by sampling Safari on iOS (on desktop the sampling was not meaningful - each execution stayed around 1-3ms)

In the following code samples + screenshots, the setup is nearly identical for each block, with a slight adaptation of wrapping the results in a S.Left/Right when using S.chain.

Note that some polyfills are installed, and this is not an absolutely pure test case (unnecessarily adds in calls to external functions, even though it's consistent and really just a map lookup) - though I figured it's better to provide _something_ and then purify later :) In the meantime, here's the data I gathered so far:

1. Vanilla

```

const startTime = performance.now();
const update = type => updated => current => ControllerIsStart (state.controller) (type) ? updated : current;

const result = 
    update (ControllerType.RENDER_MODE_WEBGL) (RenderMode.WEBGL) (
        update (ControllerType.RENDER_MODE_CANVAS) (RenderMode.CANVAS) (
            update (ControllerType.RENDER_MODE_CSS) (RenderMode.CSS) (
                update (ControllerType.RENDER_MODE_SVG) (RenderMode.SVG) (
                    state.renderMode
                )
            )
        )
    )

console.log(performance.now() - startTime);
return Object.assign({}, state, { renderMode: result });
```

![vanilla](https://user-images.githubusercontent.com/6406986/30382964-43c05b0c-98a9-11e7-858b-0a01b3008488.png)

2. Pipe

```

const startTime = performance.now();
const update = type => updated => current => ControllerIsStart (state.controller) (type) ? updated : current;

const result = 
    S.pipe([
        update (ControllerType.RENDER_MODE_SVG) (RenderMode.SVG),
        update (ControllerType.RENDER_MODE_CSS) (RenderMode.CSS),
        update (ControllerType.RENDER_MODE_CANVAS) (RenderMode.CANVAS),
        update (ControllerType.RENDER_MODE_WEBGL) (RenderMode.WEBGL)
    ])
    (state.renderMode);

console.log(performance.now() - startTime);
return Object.assign({}, state, { renderMode: result });
```

![pipe](https://user-images.githubusercontent.com/6406986/30382966-4658f7d4-98a9-11e7-94ac-ddcd6f91f2e9.png)

3. Chain

```
const startTime = performance.now();
const update = type => updated => current => ControllerIsStart (state.controller) (type) ? S.Left(updated) : S.Right(current);
     
const result = 
    S.chain(update (ControllerType.RENDER_MODE_WEBGL) (RenderMode.WEBGL)) (
        S.chain(update (ControllerType.RENDER_MODE_CANVAS) (RenderMode.CANVAS)) (
            S.chain(update (ControllerType.RENDER_MODE_CSS) (RenderMode.CSS)) (
                update (ControllerType.RENDER_MODE_SVG) (RenderMode.SVG) (
                    state.renderMode
                )
            )
        )
    ).value;

console.log(performance.now() - startTime);
return Object.assign({}, state, { renderMode: result });
```

![chain](https://user-images.githubusercontent.com/6406986/30383007-5725768c-98a9-11e7-9d23-8ab42cdde340.png)

4. Pipe + Chain

```
const startTime = performance.now();

const update = type => updated => current => ControllerIsStart (state.controller) (type) ? S.Left(updated) : S.Right(current);
     
    const result = 
    S.pipe([
        update (ControllerType.RENDER_MODE_SVG) (RenderMode.SVG),
        S.chain(update (ControllerType.RENDER_MODE_CSS) (RenderMode.CSS)),
        S.chain(update (ControllerType.RENDER_MODE_CANVAS) (RenderMode.CANVAS)),
        S.chain(update (ControllerType.RENDER_MODE_WEBGL) (RenderMode.WEBGL))
    ])
    (state.renderMode).value;

console.log(performance.now() - startTime);
return Object.assign({}, state, { renderMode: result });
```

![pipe and chain](https://user-images.githubusercontent.com/6406986/30383009-58ff460e-98a9-11e7-80c8-c9643457f8d9.png)

**Comment by dakom** [comment]
Was my mistake - the docs say pretty clearly:

> There is a performance cost to run-time type checking. One may wish to disable type checking in certain contexts to avoid paying this cost. create facilitates the creation of a Sanctuary module which does not perform type checking.

Disabling run-time type checking indeed solved the performance problem :D

**Comment by davidchambers** [comment]
Thanks for following up, @dakom.
