### ISSUE TITLE
add Either.mapLeft 

### ISSUE THREAD

**Issue by adrian-gierakowski** [sanctuary-js/sanctuary#476]
equivalent to:

```js
S.bimap( S.__, S.I )
```

trivial but handy

**Comment by davidchambers** [comment]
Good idea. I think the type would be `Bifunctor f => (a -> b) -> f a c -> f b c`.

Are you interested in submitting a pull request, @adrian-gierakowski? If so, please submit it to [sanctuary-type-classes][1]. The function will then make its way into Sanctuary itself in due course. :)


[1]: https://github.com/sanctuary-js/sanctuary-type-classes

**Comment by adrian-gierakowski** [comment]
@davidchambers thank you for adding this, and appologies for not submitting a PR myself but I haven't noticed your initial reply and forgot about the issue :)

**Comment by davidchambers** [comment]
No problem, @adrian-gierakowski. Thanks for being the catalyst. :)
