### ISSUE TITLE
submit to CDNJS

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#480]
I just found myself wanting to fetch Sanctuary from [CDNJS][1]. Let's make this possible. :)

The process of adding a library to CDNJS is daunting to the uninitiated. If you have experience with the process and would like to be involved, please speak up. :raising_hand_woman:

[1]: https://cdnjs.com/

**Comment by mfidemraizer** [comment]
It's easy. It might depend on the CDN itself. 

For example, *jsdelivr* is as easy as performing a pull request following their rules. *CDNJS* has the same process.

**Comment by Avaq** [comment]
I used https://rawgit.com for Fluture. This one just serves files straight from your git repository. Sanctuary is already hosted there: https://rawgit.com/sanctuary-js/sanctuary/master/index.js..

For Fluture I used rollup to create a bundle which includes all dependencies: https://rawgit.com/fluture-js/Fluture/master/dist/bundle.js, using this configuration: [`rollup.config.dist.js`](https://github.com/fluture-js/Fluture/blob/master/rollup.config.dist.js).

**Comment by davidchambers** [comment]
RawGit is a very useful service. I don't recommend using the `master` URL, though. ;)

> For Fluture I used rollup to create a bundle which includes all dependencies

Cool. I think we should do something similar for Sanctuary. The current process is cumbersome:

1.  Run `npm view sanctuary versions` to determine the version number of the most recent release.
2.  Run `npm view sanctuary@0.14.1 dependencies` to view the dependencies.
3.  Add a `<script>` for Sanctuary and for each dependency, using appropriate RawGit URLs.
4.  Hope that none of Sanctuary's dependencies have their own dependencies. :crossed_fingers:


[1]: https://github.com/sanctuary-js/sanctuary/blob/v0.14.1/package.json
