### ISSUE TITLE
variants of S.get, S.gets, and S.parseJson which use $.test

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#481]
Using [`$.test`][1] in conjunction with [`S.get`][2], [`S.gets`][3], or [`S.parseJson`][4] is incredibly powerful. Consider these examples:

```javascript
> S.parseJson ($.test ([]) ($.Array ($.Integer))) ('[1,2')
Nothing

> S.parseJson ($.test ([]) ($.Array ($.Integer))) ('[1,2,3]')
Just ([1, 2, 3])

> S.parseJson ($.test ([]) ($.Array ($.Integer))) ('[1,2,3,0.5]')
Nothing
```

We could provide `_`-suffixed variants for convenience:

```haskell
get_ :: Type -> String -> Any -> Maybe a
gets_ :: Type -> Array String -> Any -> Maybe a
parseJson_ :: Type -> String -> Maybe a
```

One could then write:

```javascript
> S.parseJson_ ($.Array ($.Integer)) ('[1,2')
Nothing

> S.parseJson_ ($.Array ($.Integer)) ('[1,2,3]')
Just ([1, 2, 3])

> S.parseJson_ ($.Array ($.Integer)) ('[1,2,3,0.5]')
Nothing
```

:thumbsup: / :thumbsdown: ?

[1]: https://github.com/sanctuary-js/sanctuary-def#test
[2]: https://sanctuary.js.org/#get
[3]: https://sanctuary.js.org/#gets
[4]: https://sanctuary.js.org/#parseJson

**Comment by miwillhite** [comment]
👍  I like this a lot! _Shaping_ data is one of the biggest and most important tasks I find myself in when working with the large, unkempt codebase that is my current job ;)

This is a great, non-intrusive (vs creating ADTs for everything) way of adding some safety around the data floating around my application.

**Comment by najlachamseddine** [comment]
I like it as it makes the type checking on data more explicit

**Comment by davidchambers** [comment]
#513 greatly improved the usability of [`S.get`][1], [`S.gets`][2], and [`S.parseJson`][3], so variants of these functions are no longer necessary.


[1]: https://sanctuary.js.org/#get
[2]: https://sanctuary.js.org/#gets
[3]: https://sanctuary.js.org/#parseJson
