### ISSUE TITLE
S.prop not compatible with point-free notation in Array#map

### ISSUE THREAD

**Issue by hbarcelos** [sanctuary-js/sanctuary#483]
I have the following array:

```javascript
const arr = [{ x: 1 }, { x: 2 }, { x: 3 }]
```

If I want to extract the `x` property from each item, I'd like to do:

```javascript
arr.map(S.prop('x'))
```

However, doing so raises the following error:

```
Uncaught Exception
  TypeError: Function applied to too many arguments
tooManyArguments (node_modules/sanctuary-def/index.js:2093:12)
node_modules/sanctuary-def/index.js:2446:30
node_modules/sanctuary-def/index.js:860:20
...
```

I'm aware that the [`Array#map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) argument passes down 3 arguments, but in another functional implementations, such as `ramda`, the following works:

```javascript
arr.map(R.prop('x'))
```

Of course, using a non-point-free notation works as expected:

```javascript
arr.map(d => S.prop('x', d))
```

**Comment by davidchambers** [comment]
Is there a reason to use `Array#map` rather than [`S.map`][1] in this case? I would write this instead:

```javascript
> S.map (S.prop ('x')) ([{x: 1}, {x: 2}, {x: 3}])
[1, 2, 3]
```


[1]: https://sanctuary.js.org/#map

**Comment by hbarcelos** [comment]
Yeah, that did it!
Thank's a lot @davidchambers 😃
