### ISSUE TITLE
mapMaybe on something else than an array ?

### ISSUE THREAD

**Issue by gautaz** [sanctuary-js/sanctuary#489]
Hello,

Currently this is available:
```js
S.map(S.get(S.is(Number), 'c'))({a: {c: 1}, b: {}}); // {a: Just(1), b: Nothing}
```

But this is not:
```js
S.mapMaybe(S.get(S.is(Number), 'c'))({a: {c: 1}, b: {}}); // would return {a: 1}
```

I was wondering if `mapMaybe` could be extended to operate the same way as `map`?

**Comment by davidchambers** [comment]
Great idea, @gautaz! I'll open a pull request for this improvement. :)

**Comment by Avaq** [comment]
`mapMaybe` is currently implemented as `justs(map(f, xs))`, and `justs` is specialised in Array. Now that we have Filterable, maybe we can generalise `justs` and any function implemented in terms of it.

```diff
-justs :: Array (Maybe a) -> Array a
+justs :: Filterable f => f (Maybe a) -> f a
```
