### ISSUE TITLE
`is` can be fooled

### ISSUE THREAD

**Issue by futpib** [sanctuary-js/sanctuary#502]
```js
S.is(function Number () {}, 4)
// -> true
```

While documentation says:

`is :: TypeRep a -⁠> Any -⁠> Boolean`

Takes a type representative and a value of any
type and returns `true` iff the given value is of the specified type.
Subtyping is not respected.

**Comment by davidchambers** [comment]
[`S.is`][1] predates [`$.test`][2]. Now that the latter exists I suggest using it exclusively, as it's far more expressive:

```javascript
> $.test ([]) ($.Number) (4)
true

> $.test ([]) ($.Array ($.Integer)) ([1, 2, 3])
true

> $.test ([]) ($.Array ($.Integer)) ([1, 2, 3.14])
false
```

Can we prevent `S.is` from being fooled without reintroducing the problems solved in #100?

Perhaps we should remove `S.is`. It was a reasonable stopgap, but we now have a good solution.


[1]: https://sanctuary.js.org/#is
[2]: https://github.com/sanctuary-js/sanctuary-def#test

**Comment by gautaz** [comment]
Not sure about this but perhaps `S.is` could be kept as an alias for `$.test(S.env)`?

This would break the backward compatibility with the current `S.is` but as removing it seems an option, backward compatibility will be broken anyway.

**Comment by tomkel** [comment]
Yeah, it may be cleaner API-wise to only need to interact with properties on `S`.

David, are there any downsides to this alias?

**Comment by futpib** [comment]
> only need to interact with properties on `S`.

You would need to export all type identifiers from `$` to `S` to achieve that.

**Comment by gautaz** [comment]
> You would need to export all type identifiers from $ to S to achieve that.

That's true, I was just advocating for a less radical approach such as writing things like `S.is($.Integer)` but I also understand the point raised by @tomkel.

A simple way to interact only with `S` would be something like `S.is(S.$.Integer)` but that seems ugly at first thought...

**Comment by davidchambers** [comment]
> Not sure about this but perhaps `S.is` could be kept as an alias for `$.test(S.env)`?

This is an interesting idea, @gautaz. It would make [`S.get`][1], [`S.gets`][2], and [`S.parseJson`][3] more convenient to use with `Type` values, diminishing the need for the variants proposed in #481.

@Avaq, what do you think of the possibility of repurposing [`S.is`][4]?


[1]: https://sanctuary.js.org/#get
[2]: https://sanctuary.js.org/#gets
[3]: https://sanctuary.js.org/#parseJson
[4]: https://sanctuary.js.org/#is

**Comment by Avaq** [comment]
I prefer re-purposing `S.is` over #481.
