### ISSUE TITLE
Wiki: R.always equivalency is wrong

### ISSUE THREAD

**Issue by blackxored** [sanctuary-js/sanctuary#503]
In the Wiki section "Ramda to Sanctuary" it says `K` it's equivalent to Ramda's `always`. This is not the case as `K` expects two arguments. 
You can see the output below:

<img width="359" alt="screenshot 2018-03-12 22 45 38" src="https://user-images.githubusercontent.com/133308/37311369-44618c3a-2647-11e8-9446-4473d48ee26c.png">

**Comment by davidchambers** [comment]
Very few of the equivalencies are actually interchangeable. The guide is intended to help users who know how to accomplish something with Ramda functions and would like to know how to accomplish that thing with Sanctuary functions instead. It's not realistic to expect the behaviour to match exactly.

`S.K` is the best approximation of `R.always`:

```javascript
> R.map (R.always (42)) ([1, 2, 3])
[42, 42, 42]

> S.map (S.K (42)) ([1, 2, 3])
[42, 42, 42]
```

**Comment by blackxored** [comment]
I agree, but the fact that for someone coming from Ramda, seeing this in
the Wiki is misleading.
Although the implementation here seems to be on par on how haskell’s
`const` behaves, I believe the usage that I exemplified is pretty common
(specially in `cond` pairs) and it’s misleading to have it there.
-- 
Best Regards,

Adrian Perez
https://adrianperez.codes

**Comment by davidchambers** [comment]
Would this change remove the confusion, Adrian?

```diff
-R.always(x) ~= S.K(x)
+R.always(x)() ~= S.K(x)(y)
```

**Comment by davidchambers** [comment]
> I believe the usage that I exemplified is pretty common (specially in `cond` pairs)

It's worth mentioning that `S.K` works with `R.cond` because `R.cond` provides the input value as an argument to the chosen function. :)

**Comment by blackxored** [comment]
That's true, which is exactly what's misleading about it. In some cases, like the one you mentioned, it behaves like Ramda, in some others it doesn't due to the second missing param.

**Comment by davidchambers** [comment]
I've updated the wiki entry, so I'll close this issue.

Thanks for the feedback, Adrian, and feel free to update the wiki as you see fit. :)
