### ISSUE TITLE
PR Question: Variadic Compose

### ISSUE THREAD

**Issue by mwalkerwells** [sanctuary-js/sanctuary#521]
I'd like to implement pipe with reverse arguments—any reason why a PR would not be accepted?

**Current Compose:**

<h4 name="compose"><code><a href="https://github.com/sanctuary-js/sanctuary-type-classes/blob/v7.1.1/index.js#L1380">compose :: Semigroupoid c => (c j k, c i j) -> c i k</a></code></h4>

Function wrapper for [`fantasy-land/compose`][].

`fantasy-land/compose` implementations are provided for the following
built-in types: Function.

```javascript
> compose(Math.sqrt, x => x + 1)(99)
10
```
https://github.com/sanctuary-js/sanctuary-type-classes/tree/v7.1.1#compose--semigroupoidc--cjkcij---cik

---

**Use case:**
```javascript
const foo = compose(
  Math.sqrt,
  x => x + 1,
  x => x + 1,
  x => x + 1,
  x => x + 1
)
foo(99) // 13
```

**Comment by davidchambers** [comment]
Type signatures are a critical element of Sanctuary's identity. With the exceptions of [`S.pipe`][1], [`S.get`][2], [`S.gets`][3], [`S.prop`][4], and [`S.props`][5], Sanctuary functions have types which could be expressed in Haskell and PureScript. This is an important distinction between Ramda and Sanctuary.

Haskell has no variadic functions and Hindley–Milner does not include notation for variadic functions, so Sanctuary has none. Variadic functions are unnecessary in a language with lists or arrays, particularly if the language provides syntax for list or array literals. JavaScript has arrays and array literals, so we can write `f ([x, y, z])` where one might write `f (x, y, z)` to apply a variadic function.

[`S.pipe`][1] takes an array of functions *of different types*; we had to invent notation to describe the function's type. `S.pipe` is such a useful function that we were willing to look the other way. The value of a reversed variant of `S.pipe` is significantly lower given that we already have `S.pipe` itself, so I find it hard to imagine adding such a function.

One can, of course, define such functions in one's own code. For example:

```javascript
const reversePipe = S.compose (S.pipe) (S.reverse);

const variadicCompose = (...fs) => S.pipe (S.reverse (fs));
```


[1]: https://sanctuary.js.org/#pipe
[2]: https://sanctuary.js.org/#get
[3]: https://sanctuary.js.org/#gets
[4]: https://sanctuary.js.org/#prop
[5]: https://sanctuary.js.org/#props

**Comment by mwalkerwells** [comment]
Yeah, I hear what you're saying: there are definitely trade-offs here. I'm used to infix functions with Purescript and Haskell—of course "Hindley–Milner does not include notation for variadic functions," but Javascript unfortunately doesn't have infix. 😕

I've implemented it in my open project as a function of `reverse` and `pipe`, but was just curious if you'd accept a PR. Thanks for your explantation!

**Comment by davidchambers** [comment]
> Thanks for your explantation!

You're welcome. Thanks for the proposal. :)
