### ISSUE TITLE
Why does S.sequence(S.Either) only keep the first S.Left value?

### ISSUE THREAD

**Issue by gautaz** [sanctuary-js/sanctuary#528]
Hello,

This is more a question about the `S.sequence(S.Either)` than really an issue but it might as well enlighten other people about why `S.sequence(S.Either)` is designed this way.

AFAIK, `S.Either` is assymetric by design, `S.Left` takes control over `S.Right` as `S.Left` is considered an exceptional flow compared to `S.Right` which should be the regular flow.

When a situation with multiple `S.Either` occur (i.e. an array of `S.Either`), one can "join" them by using `S.sequence(S.Either)` which results either in:
- a `S.Left` with the value of the first `S.left` of the array (there is at least one exception)
- a `S.Right` with the array of all `S.Right` values (there is no exception at all)

My question focuses on the first alternative when there is at least one `S.Left`. Why does `S.sequence(S.Either)` only keep the first exceptional value and does it not return an `S.Left` with an array of all the exceptional values?

To clarify my questioning, when I use `S.sequence(S.Either)` on an array of `S.Either`, I always feel like I am loosing all exceptional treatments I could have done if it had kept them for me. If I just really wanted to care about the first one only, I would discard the others by using `S.head` on the result but `S.sequence` does not give me this opportunity.

Is this debatable? Is there a particular reason for this that I am missing?

**Comment by masaeedu** [comment]
@gautaz The `sequence` operation comes from an instance definition of [`Traversable`](https://github.com/fantasyland/fantasy-land#traversable) from the Fantasy Land spec, which allows traversal in only one dimension (for `Either` this is the value it contains in the `Right` case).

However, it is also possible for `Either` to implement a more specific class called `Bitraversable`, as it does in Haskell. Instances of this class allow you to traverse over either of two axes in which they "contain" values. While there's no `Bitraversable` in the fantasy land spec yet, this might be a good motivating issue for adding it.

**Comment by tomkel** [comment]
I agree with gautaz's logic. From a "programming safely" perspective (which is a lot of sanctuary's motivation), more error information is better than less information.

**Comment by benperez** [comment]
If you want the "error-accumulating" behavior, you could implement your own type which does this. For an example, check out the `Data.Validation` package [here](https://hackage.haskell.org/package/validation-1).

You probably want`S.Either` to have the "first-error-only" behavior so that it can also be an instance of Monad. For an explanation of why the "error-accumulating" version can't be a monad, see [here](https://stackoverflow.com/questions/40539650/why-can-accvalidation-not-have-a-monad-instance).

**Comment by gautaz** [comment]
@tomkel Thanks for your support, the idea must still coexist with everything already in place :-).

@benperez Thanks for your insight, I am still fighting hard with everything related to category theory so forgive me if I am saying nonsense. What I was advocating for is not for `Either` to "accumulate" errors (as [data.validation](https://github.com/folktale/data.validation) is doing if I understand it correctly) but for `S.sequence(S.Either, Array S.Either)` to return a `S.Left` with an array as a value.

The latter seems likely, does what @masaeedu said about `Bitraversable` enter in contradiction with one of the laws holding everything together?

**Comment by masaeedu** [comment]
@gautaz I was actually misunderstanding your question earlier, `Bitraversable` wouldn't help you here. That only helps if you have an `Left` of an array and want to go in the other direction, i.e. producing an array of `Left`s.

**Comment by gautaz** [comment]
@masaeedu OK, I should have been more specific by detailing an example of what I would expect.

The following is **not** how `sanctuary` behaves but what I would expect:

```js
S.sequence(S.Either, [S.Right(1), S.Left(2), S.Right(3), S.Left(4)]); // S.Left([2, 4])
```

@benperez What I do not understand for now is why having `S.sequence` behaving this way implies that `S.Either` has to "accumulate" values. Please can you give me more insight on this particular point?

**Comment by gautaz** [comment]
OK looking at the [`S.Either:traverse`](https://github.com/sanctuary-js/sanctuary/blob/master/index.js#L2850) implementation of `sanctuary`, I am starting to understand the point of @benperez.
I have now to dig a little deeper in the contract that `S.traverse` must stick to in order to understand fully the issue.

**Comment by masaeedu** [comment]
@gautaz You need to look at the implementation of `Either`'s applicative instance, not its traversable, since what you're traversing is an array *containing* `Either`s. I think I might have contributed to this confusion by bringing up `Bitraversable`.

**Comment by gautaz** [comment]
@syaiful6 @masaeedu You are both right about what happened ;-). So following @syaiful6's advice, in fact `S.Either` is here used as an `Applicative`.

Looking at [Fantasy Land specification](https://github.com/fantasyland/fantasy-land), a `Monad` is not necessarily an `Applicative` but as `S.Either` is a `Monad`, it induces that `(<*>) = ap` as both @benperez ([here](https://stackoverflow.com/questions/40539650/why-can-accvalidation-not-have-a-monad-instance)) and @syaiful6 pointed out (I'm a bit slow). In my defense, I have no yet learned Haskell, I have started but I'm running out of time at the moment.

Which now leads me to get the exact meaning of `(<*>) = ap`. I have still a lot to learn which is great.  😄

**Comment by davidchambers** [comment]
Using the *right* side of `Either a b` to accumulate errors is an interesting possibility:

```javascript
const validateFoo = x => x.foo > 0                   ? S.Left (x) : S.Right (['foo must be positive']);
const validateBar = x => x.bar == S.toUpper (x.bar)  ? S.Left (x) : S.Right (['bar must be upper case']);
const validateBaz = x => x.baz.length > x.bar.length ? S.Left (x) : S.Right (['baz must be longer than bar']);

//    validate :: (Foldable f, Semigroup b) => f (a -> Either a b) -> a -> Either a b
const validate = fs => x =>
  S.reduce (S.concat)
           (S.Left (x))
           (S.map (S.T (x)) (fs));

validate ([validateFoo, validateBar, validateBaz]) ({foo: 0, bar: 'abc', baz: 'xyz'});
// => Right (['foo must be positive', 'bar must be upper case', 'baz must be longer than bar'])

validate ([validateFoo, validateBar, validateBaz]) ({foo: 0, bar: 'ABC', baz: 'xyz'});
// => Right (['foo must be positive', 'baz must be longer than bar'])

validate ([validateFoo, validateBar, validateBaz]) ({foo: 1, bar: 'ABC', baz: 'xyz'});
// => Right (['baz must be longer than bar'])

validate ([validateFoo, validateBar, validateBaz]) ({foo: 1, bar: 'ABC', baz: 'xyz!'});
// => Left ({foo: 1, bar: 'ABC', baz: 'xyz!'})
```

**Comment by gautaz** [comment]
That seems to be one way to operate some sort of aside computations while keeping all errors.
For once I feel that lefties are on the right side (I'm left-handed ;-)).

Would that mean that in order to switch between parallel and sequential operations, we would have to occasionally switch between `S.Left` and `S.Right`?

Is there an idiomatic way to *invert* a `S.Either`?

**Comment by safareli** [comment]
@davidchambers using flipped either like that means all `validate*` functions should put same value in `Left`, it means there is no need for Either and result of such functions could be `Maybe [Error]`. 

Then validate becomes:
```
validate = fs => x => foldMap((f) => f(x), fs);
```

**Comment by gautaz** [comment]
Sorry, I'm again a bit lost, I don't see `foldMap` currently available in sanctuary.
It seems close to `S.reduce`...

**Comment by davidchambers** [comment]
> I don't see `foldMap` currently available in sanctuary.

@masaeedu has opened sanctuary-js/sanctuary-type-classes#98 to define `Z.foldMap`. Once that pull request has been merged we'll be able to add `S.foldMap` to Sanctuary. :)

**Comment by gautaz** [comment]
👍 I'm looking forward to it!

I'm closing this issue for now as I guess everyone has mostly covered the ground.

Thank you all for your input which was really helpful!
