### ISSUE TITLE
Another Dumb Question: Filters?

### ISSUE THREAD

**Issue by manndave** [sanctuary-js/sanctuary#530]
Been trying to grok this all morning.  I can't seem to write a basic filter.  Here's what I've tried:
`S.filter(() => S.map(S.prop('myProp') === true))(arr);`  <-- returns my entire dataset, i.e. no filtering

`S.filter(() => S.prop('myProp') === true)(arr);`   <-- returns an empty array

What am I missing?

**Comment by Bradcomp** [comment]
In both cases you're passing a function into `filter` that doesn't take any parameters. `() => ...`

Filter should take a function that will accept an item of your list, and return a boolean. In this case, you want it to return true if the property `myProp` has a value of `true`.

`S.filter((item) => item.myProp === true)(arr)`

You could use Sanctuary functions to replace that lambda, but I think putting it that way makes it very clear.

I also want to mention that Sanctuary has a [Gitter chat room](https://gitter.im/sanctuary-js/sanctuary) as well. It might be quicker to get answers to your questions there.

**Comment by manndave** [comment]
I knew it was something stupid that I was missing...  :-(  Thanks @Bradcomp .  I had gotten myself so twisted around trying different things that I missed the easy part...

Headed over to chat room now...
