### ISSUE TITLE
Using typescript with Sanctuary?

### ISSUE THREAD

**Issue by mattgrande** [sanctuary-js/sanctuary#531]
I guess I'm wondering if I'm doing something foolish here? I'm just getting errors when I try to specify my types. Eg,

```
import * as S from 'sanctuary';

const parseNumber = (v: any): S.Maybe<number> => {
  const n = parseInt(v, 10);
  return isNaN(n) ? S.Nothing : S.Just(n);
};
```

This highlights the `S` in `S.Maybe` saying "Cannot find namespace 'S'"

I also tried importing the specific things:
```
import {Nothing, Just, Maybe, maybe} from 'sanctuary';

const parseNumber = (v: any): Maybe<number> => {
  const n = parseInt(v, 10);
  return isNaN(n) ? Nothing : Just(n);
};
```
... and that says "Cannot find name 'Maybe'."
If I change everything to `any`, it works fine, so Sanctuary is there & working, but not the types.

Versions in package.json:

    "@types/sanctuary": "0.14.2",
    "sanctuary": "0.14.1",

**Comment by davidchambers** [comment]
Should it be `import S from 'sanctuary'` rather than `import * as S from 'sanctuary'`? I don't know, I'm just suggesting something to try.

**Comment by davidchambers** [comment]
`S.Maybe<number>` doesn't look right. [`S.Maybe`][1] is not a TypeScript type constructor.


[1]: https://sanctuary.js.org/#Maybe

**Comment by mattgrande** [comment]
`import S from 'sanctuary'` works the same as `import * as...`, from what I'm seeing.

Oh well, thanks for your help.

**Comment by davidchambers** [comment]
> `S.Maybe<number>` doesn't look right. [`S.Maybe`][1] is not a TypeScript type constructor.

That is the problem. This works:

```typescript
import * as S from 'sanctuary';

interface Maybe<A> {
  constructor: {
    '@@type': 'sanctuary/Maybe';
  };
}

const parseNumber = (v: string): Maybe<number> => {
  const n = parseInt(v, 10);
  return isNaN(n) ? S.Nothing : S.Just(n);
};
```

I don't know whether it's possible to import the `Maybe` interface. You could ask the people who contributed the type definitions to [DefinitelyTyped][2].


[1]: https://sanctuary.js.org/#Maybe
[2]: https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by mattgrande** [comment]
Cool, will do.

**Comment by elie222** [comment]
Running into the same issue. Was this ever resolved?

**Comment by davidchambers** [comment]
I'm no TypeScript expert, @elie222. Does the following work for you?

```typescript
interface Maybe<A> {
  constructor: {
    '@@type': 'sanctuary-maybe/Maybe@1';
  };
}
```

**Comment by tuchk4** [comment]
@davidchambers the problem is that I should write all these internal types (`Maybe`, `Either`  etc) manually in my app :(

**Comment by deiwin** [comment]
That didn't work for me, but the following did:
```typescript
interface Maybe<A> {
  '@@type': 'sanctuary/Maybe';
}
```
