### ISSUE TITLE
lte in Ramda vs Sanctuary

### ISSUE THREAD

**Issue by jgranduel** [sanctuary-js/sanctuary#549]
Hi, 

back to sanctuary after a long while, I've been warming up...
Is there an  incompatibility here with lte ?
```
> R.lte(1) (2)
true
> S.lte(1) (2)
false
> S.filter( S.lte(2), [1, 2, 3])
[ 1, 2 ]
> R.filter( R.lte(2), [1, 2, 3])
[ 2, 3 ]
```
or 
```
> S.filter(S.lte("b"), ["a", "b", "c"])
[ 'a', 'b' ]
> R.filter(R.lte("b"), ["a", "b", "c"])
[ 'b', 'c' ]
```
In [Ramda to Sanctuary](https://github.com/sanctuary-js/sanctuary/wiki/Ramda-to-Sanctuary), 
R.lte(x, y) and S.lte(x, y) should be equivalent.

Thanks

**Comment by davidchambers** [comment]
[`S.lte`][1] and friends take their arguments in the order most natural for partial application:

> #### <code><a href="https://github.com/sanctuary-js/sanctuary/blob/v0.14.1/index.js#L594">lte</a> :: <a href="https://github.com/sanctuary-js/sanctuary-type-classes/tree/v7.1.1#Ord">Ord</a> a => a -> (a -> <a href="https://github.com/sanctuary-js/sanctuary-def/tree/v0.14.0#Boolean">Boolean</a>)</code>
>
> Returns `true` [iff][2] the *second* argument is less than or equal to the first according to [`Z.lte`][3]. The arguments must be provided one at a time.

Sanctuary:

```javascript
> S.filter (S.gte (0)) ([-27, 8, 25, -54, 25, 41])
[8, 25, 25, 41]
```

Ramda:

```javascript
> R.filter (R.gte (R.__, 0)) ([-27, 8, 25, -54, 25, 41])
[8, 25, 25, 41]
```

I hope this makes the difference clear. :)


[1]: https://sanctuary.js.org/#lte
[2]: https://en.wikipedia.org/wiki/If_and_only_if
[3]: https://github.com/sanctuary-js/sanctuary-type-classes/tree/v7.1.1#lte

**Comment by Bradcomp** [comment]
It definitely looks like the wiki page is out of date @jgranduel, thanks for bringing attention to that. Would you be interested in updating it?

**Comment by jgranduel** [comment]
Perfect!

**Comment by jgranduel** [comment]
@Bradcomp sorry I hadn't seen your comment before closing the issue. Unfortunately, I'm by far not good enough to dare comment on a very useful wiki page :(
