### ISSUE TITLE
Update head and tail to work for all Foldable

### ISSUE THREAD

**Issue by Bradcomp** [sanctuary-js/sanctuary#570]
Currently Head and Tail only work for `Array`, but it is possible to implement them for all `Foldable`.

**Comment by Bradcomp** [comment]
Sample `head` implementation:

`const f = S.reduce(b => a => S.maybe(S.Just(a))(_ => b)(b))(S.Nothing)`

Sample, but incomplete `tail` implementation:

```
const tail = xs => {
  let skipped = false;
  return Z.reduce ((xs, x) => {
    if (skipped) {
      return Z.append (x, xs);
    } else {
      skipped = true;
      return xs;
    }
  }, [], xs);
};

```

**Comment by masaeedu** [comment]
Here's a complete `tail` implementation:

```js
// tail :: (Foldable f, Applicative g, Monoid g) => TypeRep g -> f a -> Maybe (g a)
const tail = tr =>
  S.reduce(b => a =>
    S.maybe
      (S.Just(Z.empty(tr)))
      (x => S.Just(Z.concat(x, Z.of(tr, a))))
      (b)
  )(S.Nothing);

[tail(Array)([]), tail(Array)([1]), tail(Array)([1, 2]), tail(Array)([1, 2, 3])]
// => [Nothing, Just ([]), Just ([2]), Just ([2, 3])]
```

**Comment by davidchambers** [comment]
@Bradcomp and @masaeedu, would one of you like to add these functions to sanctuary-type-classes?

**Comment by davidchambers** [comment]
@syves has expressed interest in working on these generalizations. While we're at it, let's generalize [`S.last`][1] and [`S.init`][2]. These are the desired signatures (constraints omitted with pedagogy in mind):

```haskell
S.head :: ??? => f a -> Maybe a
S.last :: ??? => f a -> Maybe a
S.tail :: ??? => f a -> Maybe (f a)
S.init :: ??? => f a -> Maybe (f a)
```


[1]: https://github.com/sanctuary-js/sanctuary/tree/v0.15.1#last
[2]: https://github.com/sanctuary-js/sanctuary/tree/v0.15.1#init
