### ISSUE TITLE
Easy Question: Type Errors

### ISSUE THREAD

**Issue by mwalkerwells** [sanctuary-js/sanctuary#583]
```js
chain :: Chain m => (a -> m b) -> m a -> m b
                          ^^^     ^^^
                           1       2

1)  Future.of(Right ("Hello")) :: Future c (Either d String)
2)  Right ({ /*...*/ }) :: Either c Object, Either c (StrMap Object)
// ———————————————————————————————————————^
```

What does the comma mean? Union?

**Comment by davidchambers** [comment]
A value can be a member of multiple types. `0`, for example, is a member of the following types:

  - [`Number`][1]
  - [`ValidNumber`][2]
  - [`FiniteNumber`][3]
  - [`Integer`][4]
  - [`NonNegativeInteger`][5]

These types are listed on a single line in error messages, separated by commas. For example:

```javascript
S.toUpper (0);
// ! TypeError: Invalid value
//
//   toUpper :: String -> String
//              ^^^^^^
//                1
//
//   1)  0 :: Number, FiniteNumber, Integer, NonNegativeInteger, ValidNumber
//
//   The value at position 1 is not a member of ‘String’.
//
//   See https://github.com/sanctuary-js/sanctuary-def/tree/v0.18.1#String for information about the String type.
```


[1]: https://github.com/sanctuary-js/sanctuary-def#Number
[2]: https://github.com/sanctuary-js/sanctuary-def#ValidNumber
[3]: https://github.com/sanctuary-js/sanctuary-def#FiniteNumber
[4]: https://github.com/sanctuary-js/sanctuary-def#Integer
[5]: https://github.com/sanctuary-js/sanctuary-def#NonNegativeInteger

**Comment by mwalkerwells** [comment]
Ah, makes sense! Thank you!
