### ISSUE TITLE
Duplicate absMid ("sanctuary-type-identifiers") 

### ISSUE THREAD

**Issue by soeik** [sanctuary-js/sanctuary#584]
Just installed sanctuary with `npm install sanctuary --save` and got following in my webpack-dev-server.
Trying to build project with webpack gives same result:

`Duplicate absMid ("sanctuary-type-identifiers") for modules "***\\node_modules\\sanctuary-type-classes\\node_modules\\sanctuary-type-identifiers\\index.js" and "***\\node_modules\\sanctuary-type-identifiers\\index.js"`

Couldn't find anything in google regarding such error message.

**Comment by davidchambers** [comment]
Please reopen this issue if you're still experiencing this problem, @soeik.
