### ISSUE TITLE
How to use partial application here?

### ISSUE THREAD

**Issue by uldaman** [sanctuary-js/sanctuary#585]
Because of some functions in other library, I can't apply its parameters in order. So, do we have a feature that looks  like `R.__` in Ramda?

**Comment by davidchambers** [comment]
We removed the placeholder functionality when we switched from Ramda-style currying to simple currying. One can, though, use [`S.flip`][1]:

```javascript
> S.concat ('foo') ('bar')
'foobar'

> S.flip (S.concat) ('bar') ('foo')
'foobar'
```


[1]: https://sanctuary.js.org/#flip

**Comment by uldaman** [comment]
Ok, got it, thank you.
