### ISSUE TITLE
fix: used with sanctuary-def environments some functions throw type errors

### ISSUE THREAD

**Issue by rockymadden** [sanctuary-js/sanctuary#587]
When using `sanctuary` with `checkTypes` set to true and the environment set to a barebones `sanctuary-def` environment, some functions throw type errors with valid usage. These include, but may not be limited to:

* `flip`
* `compose`

Ref: https://repl.it/@rockymadden/break-sanctuary-flip

P.S. I acknowledge this might be a `sanctuary-def` bug, but observing the behavior here in `sanctuary` I thought I'd add here off-the-cuff.

**Comment by davidchambers** [comment]
Why [`$.env`][1] rather than [`S.env`][2]?


[1]: https://github.com/sanctuary-js/sanctuary-def#env
[2]: https://sanctuary.js.org/#env

**Comment by rockymadden** [comment]
@davidchambers In the scenario provided, there would be no reason to do so. In a real world example, I might be using Fluture and custom types in my environment.

**Comment by davidchambers** [comment]
I'm curious as to why you augment `$.env` rather than `S.env`.

Is it reasonable for Sanctuary functions to rely on types included in `S.env` but not in `$.env`?

**Comment by rockymadden** [comment]
Interesting. There is not specific reason I did it that way beside assuming it didn't matter. However, I do see what you are saying and some other potential benefits as well. Let me invert and touch base.

**Comment by rockymadden** [comment]
Yep, this did indeed do the trick. Thank you, kindly, for that tidbit.

**Comment by davidchambers** [comment]
You're welcome, Rocky. :)
