### ISSUE TITLE
Major version bump to 1.0

### ISSUE THREAD

**Issue by Siilwyn** [sanctuary-js/sanctuary#588]
:wave: Wondering what is holding back a 1.0 release, maybe a case of what Germans would call Hauptversionsnummernerhöhungsangst? The fear of a major bump. As Stephan Bönnemann (who is arguing hard for semver and did talks on the subject), loosely quoted:
> Version numbers should be used to avoid dependency hell... There's no reason for keeping the version number low, expect for marketing or maybe emotional attachment to versions. There's this concept in our mind that the version number has something to say about the project or the process or the stability and all of this is wrong... People believe something incredible existing is happening when a major/breaking version is released...

Please consider following semver, it doesn't mean the project is suddenly 'done' or has changed. It just gives users context about the change and reliability that patch and minor changes won't break their code base.

Let me know if I can help out!

**Comment by davidchambers** [comment]
> Please consider following semver

We do! ;)

> Wondering what is holding back a 1.0 release

The next release will be tagged `v1.0.0`. It will include a small number of changes and documentation improvements. From that point forward, breaking changes will only be made in major releases. :)

**Comment by Siilwyn** [comment]
> We do! ;)

Okay technically you do, practically you don't. ^^

> The next release will be tagged `v1.0.0`. It will include a small number of changes and documentation improvements. From that point forward, breaking changes will only be made in major releases. :)

Great, looking forward to it! :confetti_ball: I hope you don't mind keeping this issue open until then, that way I get notified. Otherwise feel free to close.

**Comment by davidchambers** [comment]
> I hope you don't mind keeping this issue open until then, that way I get notified.

No problem. :)

**Comment by davidchambers** [comment]
<https://github.com/sanctuary-js/sanctuary/releases/tag/v1.0.0>

**Comment by Siilwyn** [comment]
Awesome! :confetti_ball:
