### ISSUE TITLE
Function Signature formatting makes it more difficult to search for Haskell or PureScript equivalents

### ISSUE THREAD

**Issue by kurtmilam** [sanctuary-js/sanctuary#647]
It would be nice to be able to copy a function signature from SanctuaryJS docs and paste it into [Hoogle](https://hoogle.haskell.org/) or [Pursuit](https://pursuit.purescript.org/) to find equivalent or similar functions in Haskell or PureScript.

Unfortunately, the use of `WORD JOINER` / `U+2060` in `->` and friends in SanctuaryJS function signatures makes it harder to do this.

Searching for the Haskell and PureScript equivalent of Sanctuary's `chain` function (fn sig copied directly from the SanctuaryJS docs):

[Haskell](https://hoogle.haskell.org/?hoogle=(a%20-%E2%81%A0%3E%20m%20b)%20-%E2%81%A0%3E%20m%20a%20-%E2%81%A0%3E%20m%20b):
![image](https://user-images.githubusercontent.com/385695/63288237-7e4b1200-c2bc-11e9-9a29-923ea96829d6.png)
---
[PureScript](https://pursuit.purescript.org/search?q=%28a+-%E2%81%A0%3E+m+b%29+-%E2%81%A0%3E+m+a+-%E2%81%A0%3E+m+b):
![image](https://user-images.githubusercontent.com/385695/63288193-683d5180-c2bc-11e9-98ca-cd96aab21ff1.png)
---
[Ramda](https://ramdajs.com/docs/) uses the `→` character, which works in Pursuit, but not in Hoogle:
![image](https://user-images.githubusercontent.com/385695/63288400-e4d03000-c2bc-11e9-918e-1e98fa6d63ba.png)
---

**Comment by CrossEye** [comment]
Yes, I want to fix this in Ramda too; it's just never made it to the top of the list.  What I really want to do is to use [`Fira Code`][fc], a font with programmers' ligatures, which I first noticed on Tom Harding's site (for example, on his [Setoid overview][se].)

This would allow users to cut and paste `->` but still have it appear as a readable arrow.

I think this would improve things quite a bit.


  [fc]: https://github.com/tonsky/FiraCode
  [se]: http://www.tomharding.me/2017/03/09/fantas-eel-and-specification-3/

**Comment by kurtmilam** [comment]
@CrossEye I use `Fira` in VSCode, where I mostly write PureScript (still learning), but I also take advantage of the fact that PureScript allows unicode characters like `∷`, `∀`, `⇒` and `→` :)

Examples:
![image](https://user-images.githubusercontent.com/385695/63290095-0206fd80-c2c1-11e9-9e06-88a7d6944398.png)

![image](https://user-images.githubusercontent.com/385695/63290168-2662da00-c2c1-11e9-8882-52119ced7f73.png)

**Comment by davidchambers** [comment]
@kurtmilam, might it be possible to write a few lines of JavaScript to intercept the copy event?

@CrossEye, if you have Fira Code installed you should see it in use on the Sanctuary website.

**Comment by CrossEye** [comment]
@davidchambers: Interesting.  When I tried copying the `chain` signature to Hoogle earlier in the day, I got the same result that Kurt described.  Now it works fine.  Did this change recently, or could it be a difference between Windows and Ubuntu?

**Comment by davidchambers** [comment]
@CrossEye, were you copying from the website or from the readme? The script that generates the website [removes WORD JOINER characters][1].


[1]: https://github.com/sanctuary-js/sanctuary-site/blob/1d6b7d91796f0fd89bda850fbd8c53e2980d0232/scripts/generate#L183

**Comment by kurtmilam** [comment]
@davidchambers That sounds like an interesting solution. I'll do some research as soon as I get a chance.

I'm on a Mac and copied the sigs from the readme, btw.

**Comment by davidchambers** [comment]
> That sounds like an interesting solution. I'll do some research as soon as I get a chance.

My suggestion was misleading. I mistakenly assumed the problem applies to the website, but after investigating I convinced myself that it only applies to the readme.

I'm ready to revert plaid/transcribe#14, as it introduced more problems than it solved (in addition to the copy and paste problem, Safari incorrectly renders WORD JOINER characters as spaces).

@kurtmilam, if you have a chance please [open an issue][1] and include a link to this one. I think further discussion should take place in Transcribe's issue tracker.


[1]: https://github.com/plaid/transcribe/issues/new

**Comment by kurtmilam** [comment]
Ah, OK. I had just worked out a solution to remove the WORD JOIN character on the copy event and was going to see how / whether it was possible to run javascript on a GitHub `md` page 😄

**Comment by CrossEye** [comment]
@davidchambers: Perhaps I switched from one to the other when I switched from work (Windows) to home (Mac).  I didn't check.

**Comment by kurtmilam** [comment]
Also, for posterity, the screenshots I shared above, which I thought were of Fira Code were actually of Hasklig, which also supports ligatures.

I had specified `Fira Code` as the primary font in my editor, but I'd somehow managed to bungle font's installation.

I've rectified that now 😄

**Comment by Bradcomp** [comment]
@kurtmilam OT, but I prefer Hasklig to Fira anyway because Fira is too skinny for me anyway. :wink:

I was using a fork of Hasklig called Blackfont for a while that had better support for JS ligatures, but still looks the same.

Now I am using the ligature variant of [Fantasque Sans](https://github.com/belluzj/fantasque-sans/issues/64#issuecomment-355789531) which is more pleasing to my eyes but has less ligatures.
