### ISSUE TITLE
Typescript mapLeft not found

### ISSUE THREAD

**Issue by edgarjrg** [sanctuary-js/sanctuary#648]
Hi! Incredible library 👏 thank you  🙏 

I'm using Sanctuary with Typescript (@types/sanctuary@0.14.2) and the type of S.mapLeft does not appear anywhere, so i'm unable to use the function.

Is there any way i could contribute to add this type or maybe there is a workarround or is included in another version? 

Thank you in advance 🙏

**Comment by davidchambers** [comment]
@vicrac and I are updating Sanctuary's type definitions in DefinitelyTyped/DefinitelyTyped#37879. I have encountered several problems as a result of TypeScript's lack of higher-kinded types and its intentionally simplistic type resolution algorithm that replaces many type variables with `any`.

Let's move this discussion to the aforementioned pull request. :)
