### ISSUE TITLE
toEither :: a -> b? -> Either a b

### ISSUE THREAD

**Issue by davidchambers** [sanctuary-js/sanctuary#83]
Suggested by @raine on [Gitter][1].

```javascript
> S.toEither('Invalid protocol', 'ftp://example.com/'.match(/^(http:|https:)[/][/]/))
Left("Invalid protocol")

> S.toEither('Invalid protocol', 'http://example.com/'.match(/^(http:|https:)[/][/]/))
Right(["http://", "http:"])
```

This would mirror [`S.toMaybe`][2].

[1]: https://gitter.im/plaid/sanctuary
[2]: https://github.com/plaid/sanctuary#toMaybe

**Comment by raine** [comment]
If you want to have an Error object inside `Left`, you'd have to do something like this to get a sensible stacktrace.

```js
S.toEither(new Error('Invalid protocol'), 'http://example.com/'.match(/^(http:|https:)[/][/]/))
```

Creating unneeded Error objects doesn't seem like a good idea, at least from performance point of view. Taking a function as first argument would solve this, but does it make the API too focused on that particular use case?

**Comment by davidchambers** [comment]
I'd probably use [`R.ifElse`][1] in that case:

```javascript
// protocol :: String -> Either Error String
const protocol =
R.pipe(R.match(/^(http:|https:)[/][/]/),
       R.ifElse(R.isEmpty,
                () => S.Left(new Error('Invalid protocol')),
                S.Right),
       R.map(R.nth(1)));

protocol('ftp://example.com/');
// => Left(Error: Invalid protocol)
protocol('http://example.com/');
// => Right("http:")
```

Perhaps, though, we could have a second function of type `String -> a? -> Either Error a`. The function would create an Error object with the specified message if necessary. I don't want to rush into adding such a function. I'm wary whenever we deviate from the path paved by Haskell and PureScript.


[1]: http://ramdajs.com/docs/#ifElse

**Comment by davidchambers** [comment]
Sounds good, @rjmk. :)
