### ISSUE TITLE
Mapping the left side of an Either

### ISSUE THREAD

**Issue by raine** [sanctuary-js/sanctuary#98]
Let's explore if these functions in [`data.either`](https://github.com/folktale/data.either) would be useful in Sanctuary:
- [`orElse`](https://github.com/folktale/data.either/blob/master/lib/either.js#L313-L315)
- [`bimap`](https://github.com/folktale/data.either/blob/master/lib/either.js#L380-L394)
- [`leftMap`](https://github.com/folktale/data.either/blob/master/lib/either.js#L397-L408)

**Comment by benperez** [comment]
Nice suggestions! In Haskell [Data.Either is an instance of Data.Bifunctor](http://hackage.haskell.org/package/base-4.8.1.0/docs/Data-Either.html#v:bimap). Which would give us `bimap`, `first` (or `leftMap`), and `second` (or `rightMap`/`fmap`). `orElse` seems interesting too, what's an example use case for that?

**Comment by benperez** [comment]
I'm going to go ahead and take a crack at `leftMap` and `biMap`. @albrow and I had a need for this earlier today.

**Comment by davidchambers** [comment]
Are you still interested in working on this, @benperez? If not, I'm happy to investigate these options.

**Comment by blperez** [comment]
I can check it out this weekend after I submit my ramda PR.

**Comment by davidchambers** [comment]
That would be wonderful!

**Comment by benperez** [comment]
@blperez is an imposter, I'll take a look when if I get a chance this weekend.

**Comment by iliocatallo** [comment]
any news on this side?

**Comment by davidchambers** [comment]
I think we should implement `Either#bimap` in accordance with fantasyland/fantasy-land#137:

```haskell
Either#bimap :: Either a b ~> (a -> c) -> (b -> d) -> Either c d
```

I'm preparing to move to a different continent in a couple of days, but I should be able to devote significant time to Sanctuary once I'm in Europe. If you'd like to contribute a pull request for this addition, though, please do so. :)

**Comment by jlmorgan** [comment]
`orElse`, `orElseGet` and `orElseThrow` are tied to `extract`/`get`.

Examples:

```javascript
S.Right(1).extract();
// => 1
S.Left("NaN").extract();
// => ?

S.Right(1).orElse(2);
// => 1
S.Left("NaN").orElse(2);
// => 2

S.Right(1).orElseGet(() => 2);
// => 1
S.Left("NaN").orElseGet(() => 2);
// => 2

S.Right(1).orElseThrow(() => new Error("fatal: because reasons");
// => 1
S.Left("NaN").orElseThrow(() => new Error("fatal: because reasons");
// => throws Error
```

With `extract` being a possible mixed type, you would likely end up with `getOrElse`, `getOrElseGet`, and `getOrElseThrow` to avoid marrying to `Comonad`.

**Comment by davidchambers** [comment]
> With `extract` being a possible mixed type

In other words, `Either a b` cannot support [`extract`][1].


[1]: https://github.com/fantasyland/fantasy-land#extract-method

**Comment by jlmorgan** [comment]
Basically. Hence the `get` prefixed versions of the method that require you to provide a fallback value.

**Comment by jlmorgan** [comment]
Static versions come in handy when going through a map as well rather than having to purge all the lefts/nothings/failures.

**Comment by davidchambers** [comment]
Thanks to #229 we have `fromEither :: b -> Either a b -> b`. :)
